import { CorporateContract } from "../types/corporate";

export const mockContracts: CorporateContract[] = [
  {
    id: "CTR-2026-001",
    contractNumber: "CTR-2026-001",
    corporateCustomerId: "CORP-001",
    corporateCustomerName: "PT ABC Indonesia",
    startDate: "2026-01-01",
    endDate: "2026-12-31",
    status: "ACTIVE",
    monthlyBillingAmount: 145000000,
    paymentTerm: "Net 30",
    requiredFleet: 10,
    allocatedFleet: 10,
    operationalFleet: 9,
    maintenanceFleet: 1,
    replacementFleet: 0,
    shortageCount: 1, // Shortage detected! Needs replacement
    allocatedVehicles: [
      {
        vehicleId: "B-1234-XYZ",
        plateNumber: "B 1234 XYZ",
        model: "Toyota Innova Zenix 2.0 V CVT",
        ownership: "JAJA_OWNED",
        assignedDriver: "Budi Santoso",
        status: "OPERATIONAL",
        location: "SCBD Jakarta",
        odometer: 82421,
      },
      {
        vehicleId: "B-8899-KLU",
        plateNumber: "B 8899 KLU",
        model: "Mitsubishi Xpander Ultimate",
        ownership: "JAJA_OWNED",
        assignedDriver: "Ahmad Riyadi",
        status: "MAINTENANCE", // Under maintenance!
        location: "AutoCare Pulogadung",
        odometer: 58920,
      },
      {
        vehicleId: "B-5678-ABC",
        plateNumber: "B 5678 ABC",
        model: "Toyota Veloz 1.5 Q CVT",
        ownership: "JAJA_OWNED",
        assignedDriver: "Yudi Purnomo",
        status: "OPERATIONAL",
        location: "Jakarta Barat",
        odometer: 45210,
      },
      {
        vehicleId: "B-2211-KKK",
        plateNumber: "B 2211 KKK",
        model: "Toyota Innova Zenix 2.0 G",
        ownership: "JAJA_OWNED",
        assignedDriver: "Dodi Hartanto",
        status: "OPERATIONAL",
        location: "Jakarta Timur",
        odometer: 24500,
      },
      {
        vehicleId: "B-3344-ZZA",
        plateNumber: "B 3344 ZZA",
        model: "Hyundai Stargazer Prime",
        ownership: "JAJA_OWNED",
        assignedDriver: "Indra Lesmana",
        status: "OPERATIONAL",
        location: "Jakarta Selatan",
        odometer: 28400,
      },
      {
        vehicleId: "B-4422-RST",
        plateNumber: "B 4422 RST",
        model: "Toyota Innova Reborn 2.4 G",
        ownership: "VENDOR_OWNED",
        assignedDriver: "Supriyanto",
        status: "OPERATIONAL",
        location: "Bekasi",
        odometer: 98400,
      },
      {
        vehicleId: "B-5566-VBN",
        plateNumber: "B 5566 VBN",
        model: "Mitsubishi Pajero Sport 2.4",
        ownership: "VENDOR_OWNED",
        assignedDriver: "Guntur Pratama",
        status: "OPERATIONAL",
        location: "Jakarta Utara",
        odometer: 64120,
      },
      {
        vehicleId: "B-6721-EDC",
        plateNumber: "B 6721 EDC",
        model: "Toyota Fortuner 2.4 VRZ",
        ownership: "VENDOR_OWNED",
        assignedDriver: "Rahmat Hidayat",
        status: "OPERATIONAL",
        location: "Jakarta Selatan",
        odometer: 89300,
      },
      {
        vehicleId: "B-3199-OPP",
        plateNumber: "B 3199 OPP",
        model: "Hyundai Stargazer Active",
        ownership: "JAJA_OWNED",
        assignedDriver: "Joko Susilo",
        status: "OPERATIONAL",
        location: "Jakarta Utara",
        odometer: 54100,
      },
      {
        vehicleId: "B-5012-YTR",
        plateNumber: "B 5012 YTR",
        model: "Mitsubishi Xpander Cross",
        ownership: "JAJA_OWNED",
        assignedDriver: "Agus Maulana",
        status: "OPERATIONAL",
        location: "Bekasi",
        odometer: 37400,
      },
    ],
    notes:
      "VIP Contract. Requires 1 replacement unit for unit B 8899 KLU currently undergoing brake overhaul.",
  },
  {
    id: "CTR-2026-002",
    contractNumber: "CTR-2026-002",
    corporateCustomerId: "CORP-002",
    corporateCustomerName: "PT Maju Bersama",
    startDate: "2026-02-01",
    endDate: "2027-01-31",
    status: "ACTIVE",
    monthlyBillingAmount: 104000000,
    paymentTerm: "Net 45",
    requiredFleet: 8,
    allocatedFleet: 8,
    operationalFleet: 8,
    maintenanceFleet: 0,
    replacementFleet: 0,
    shortageCount: 0,
    allocatedVehicles: [],
    notes: "Standard operational contract for factory management in Cikarang.",
  },
  {
    id: "CTR-2026-003",
    contractNumber: "CTR-2026-003",
    corporateCustomerId: "CORP-003",
    corporateCustomerName: "PT Nusantara Logistik",
    startDate: "2025-11-01",
    endDate: "2026-10-31",
    status: "EXPIRING_SOON",
    monthlyBillingAmount: 225000000,
    paymentTerm: "Net 30",
    requiredFleet: 15,
    allocatedFleet: 15,
    operationalFleet: 14,
    maintenanceFleet: 1,
    replacementFleet: 0,
    shortageCount: 1,
    allocatedVehicles: [],
    notes:
      "Contract expires in less than 60 days. Renewal proposal in progress.",
  },
  {
    id: "CTR-2026-004",
    contractNumber: "CTR-2026-004",
    corporateCustomerId: "CORP-004",
    corporateCustomerName: "PT Sinar Abadi",
    startDate: "2026-05-01",
    endDate: "2027-04-30",
    status: "ACTIVE",
    monthlyBillingAmount: 88000000,
    paymentTerm: "Net 30",
    requiredFleet: 6,
    allocatedFleet: 6,
    operationalFleet: 6,
    maintenanceFleet: 0,
    replacementFleet: 0,
    shortageCount: 0,
    allocatedVehicles: [],
  },
  {
    id: "CTR-2026-005",
    contractNumber: "CTR-2026-005",
    corporateCustomerId: "CORP-005",
    corporateCustomerName: "PT Mandiri Distribusi",
    startDate: "2026-03-01",
    endDate: "2027-02-28",
    status: "ACTIVE",
    monthlyBillingAmount: 180000000,
    paymentTerm: "Net 30",
    requiredFleet: 12,
    allocatedFleet: 12,
    operationalFleet: 12,
    maintenanceFleet: 0,
    replacementFleet: 0,
    shortageCount: 0,
    allocatedVehicles: [],
  },
];
