import { IndividualCustomer, CorporateCustomer } from "../types/customer";

export const mockIndividualCustomers: IndividualCustomer[] = [
  // 1. Fully ELIGIBLE ACTIVE Customer (KTP verified, SIM valid, T&C v1.3 accepted)
  {
    id: "CUST-001",
    type: "INDIVIDUAL",
    name: "Hendrawan Putra",
    nik: "3174051908850002",
    phone: "+62 812-9988-1234",
    email: "hendrawan.putra@gmail.com",
    dateOfBirth: "1985-08-19",
    address: "Jl. Senopati No. 45, Kebayoran Baru",
    city: "Jakarta Selatan",
    province: "DKI Jakarta",
    postalCode: "12190",
    status: "ACTIVE",
    joinedDate: "2024-02-10",
    totalRentalsCount: 5,
    activeRentalsCount: 1,
    drivingInfo: {
      licenseNumber: "SIM-A-99210034",
      licenseType: "SIM_A",
      licenseExpiry: "2028-08-19",
      yearsOfExperience: 8,
      verificationStatus: "VERIFIED",
    },
    emergencyContact: {
      name: "Siti Rahmawati",
      relationship: "SPOUSE",
      phone: "+62 812-9988-5678",
      address: "Jl. Senopati No. 45, Jakarta Selatan",
    },
    documents: [
      {
        id: "DOC-CUST001-KTP",
        documentType: "KTP",
        documentName: "KTP Elektronik",
        documentNumber: "3174051908850002",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Rudi Hartono (QC Jaja)",
        verifiedDate: "2024-02-10",
        fileName: "KTP_Hendrawan.jpg",
        fileUrl: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=600&auto=format&fit=crop&q=80",
      },
      {
        id: "DOC-CUST001-SIM",
        documentType: "SIM",
        documentName: "Surat Izin Mengemudi (SIM A)",
        documentNumber: "SIM-A-99210034",
        expiryDate: "2028-08-19",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Rudi Hartono (QC Jaja)",
        verifiedDate: "2024-02-10",
        fileName: "SIM_A_Hendrawan.jpg",
        fileUrl: "https://images.unsplash.com/photo-1549399542-7e3f8b79c341?w=600&auto=format&fit=crop&q=80",
      },
      {
        id: "DOC-CUST001-NPWP",
        documentType: "NPWP",
        documentName: "NPWP Pribadi",
        documentNumber: "88.123.456.7-012.000",
        isRequired: false,
        verificationStatus: "VERIFIED",
        verifiedBy: "Rudi Hartono (QC Jaja)",
        verifiedDate: "2024-02-10",
        fileName: "NPWP_Hendrawan.jpg",
      },
    ],
    agreements: [
      {
        id: "ACC-2026-001",
        customerId: "CUST-001",
        agreementId: "AGR-B2C-V1.3",
        agreementType: "B2C_RENTAL_TERMS",
        agreementVersion: "1.3",
        acceptedAt: "2026-09-01T08:30:00Z",
        acceptedBy: "Hendrawan Putra",
        acceptedByRole: "Penyewa Utama",
        acceptedByPhone: "+62 812-9988-1234",
        acceptedByEmail: "hendrawan.putra@gmail.com",
        ipAddress: "182.253.44.12",
        status: "ACCEPTED",
        acceptedClauses: [
          "CLAUSE-B2C-01",
          "CLAUSE-B2C-02",
          "CLAUSE-B2C-03",
          "CLAUSE-B2C-04",
          "CLAUSE-B2C-05",
          "CLAUSE-B2C-06",
        ],
        digitalConsentNote: "Disetujui melalui SMS OTP Verifikasi Jaja-Rent Platform.",
      },
    ],
  },

  // 2. BLOCKED Customer (Active account but SIM EXPIRED & Pending Agreement v1.3)
  {
    id: "CUST-002",
    type: "INDIVIDUAL",
    name: "Jessica Tanuwidjaja",
    nik: "3671045502920001",
    phone: "+62 817-8822-1100",
    email: "jessica.t@tanuwidjaja.id",
    dateOfBirth: "1992-02-15",
    address: "Cluster Greenwich Park, BSD City",
    city: "Tangerang",
    province: "Banten",
    postalCode: "15330",
    status: "ACTIVE",
    joinedDate: "2024-03-12",
    totalRentalsCount: 3,
    activeRentalsCount: 0,
    drivingInfo: {
      licenseNumber: "SIM-A-88129033",
      licenseType: "SIM_A",
      licenseExpiry: "2026-08-15", // EXPIRED!
      yearsOfExperience: 5,
      verificationStatus: "EXPIRED",
    },
    emergencyContact: {
      name: "David Tanuwidjaja",
      relationship: "FAMILY",
      phone: "+62 817-8822-9999",
    },
    documents: [
      {
        id: "DOC-CUST002-KTP",
        documentType: "KTP",
        documentName: "KTP Elektronik",
        documentNumber: "3671045502920001",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Bambang Irawan",
        verifiedDate: "2024-03-12",
      },
      {
        id: "DOC-CUST002-SIM",
        documentType: "SIM",
        documentName: "Surat Izin Mengemudi (SIM A)",
        documentNumber: "SIM-A-88129033",
        expiryDate: "2026-08-15",
        isRequired: true,
        verificationStatus: "EXPIRED",
        verifiedBy: "Bambang Irawan",
        verifiedDate: "2024-03-12",
        notes: "Masa berlaku SIM telah habis per 15 Agustus 2026, butuh perpanjangan.",
      },
    ],
    agreements: [
      // Only accepted old version 1.2, not current 1.3
      {
        id: "ACC-2025-089",
        customerId: "CUST-002",
        agreementId: "AGR-B2C-V1.2",
        agreementType: "B2C_RENTAL_TERMS",
        agreementVersion: "1.2",
        acceptedAt: "2025-06-10T10:15:00Z",
        acceptedBy: "Jessica Tanuwidjaja",
        ipAddress: "114.122.90.18",
        status: "ACCEPTED",
        acceptedClauses: ["CLAUSE-B2C-01", "CLAUSE-B2C-02"],
      },
    ],
  },

  // 3. DOCUMENT_REVIEW Stage Customer
  {
    id: "CUST-003",
    type: "INDIVIDUAL",
    name: "Raditya Dika Pratama",
    nik: "3174032104880004",
    phone: "+62 811-3322-110",
    email: "raditya.dp@gmail.com",
    dateOfBirth: "1988-04-21",
    address: "Jl. Kemang Timur No. 18",
    city: "Jakarta Selatan",
    province: "DKI Jakarta",
    postalCode: "12730",
    status: "DOCUMENT_REVIEW",
    joinedDate: "2026-08-30",
    totalRentalsCount: 0,
    activeRentalsCount: 0,
    drivingInfo: {
      licenseNumber: "SIM-A-77341209",
      licenseType: "SIM_A",
      licenseExpiry: "2029-04-21",
      yearsOfExperience: 6,
      verificationStatus: "PENDING",
    },
    emergencyContact: {
      name: "Pratama Senior",
      relationship: "PARENT",
      phone: "+62 811-3322-999",
    },
    documents: [
      {
        id: "DOC-CUST003-KTP",
        documentType: "KTP",
        documentName: "KTP Elektronik",
        documentNumber: "3174032104880004",
        isRequired: true,
        verificationStatus: "PENDING",
        fileName: "KTP_Raditya.jpg",
      },
      {
        id: "DOC-CUST003-SIM",
        documentType: "SIM",
        documentName: "Surat Izin Mengemudi (SIM A)",
        documentNumber: "SIM-A-77341209",
        expiryDate: "2029-04-21",
        isRequired: true,
        verificationStatus: "PENDING",
        fileName: "SIM_Raditya.jpg",
      },
    ],
    agreements: [],
  },

  // 4. NEED_REVISION Customer (Blurry document)
  {
    id: "CUST-004",
    type: "INDIVIDUAL",
    name: "Maya Safitri",
    nik: "3173026809930005",
    phone: "+62 813-9911-2288",
    email: "maya.safitri@yahoo.co.id",
    dateOfBirth: "1993-09-28",
    address: "Apartemen Medit 2 Tower Jasmine, Tanjung Duren",
    city: "Jakarta Barat",
    province: "DKI Jakarta",
    postalCode: "11470",
    status: "NEED_REVISION",
    joinedDate: "2026-08-28",
    totalRentalsCount: 0,
    activeRentalsCount: 0,
    reviewNotes: "Foto KTP buram dan nomor NIK tidak terbaca jelas. Mohon upload ulang foto KTP dengan pencahayaan cukup.",
    drivingInfo: {
      licenseNumber: "SIM-A-55910244",
      licenseType: "SIM_A",
      licenseExpiry: "2028-09-28",
      verificationStatus: "VERIFIED",
    },
    emergencyContact: {
      name: "Budi Santoso",
      relationship: "COLLEAGUE",
      phone: "+62 813-9911-0000",
    },
    documents: [
      {
        id: "DOC-CUST004-KTP",
        documentType: "KTP",
        documentName: "KTP Elektronik",
        documentNumber: "3173026809930005",
        isRequired: true,
        verificationStatus: "NEED_REVISION",
        rejectionReason: "Foto KTP buram/blur, silau lampu.",
      },
      {
        id: "DOC-CUST004-SIM",
        documentType: "SIM",
        documentName: "Surat Izin Mengemudi (SIM A)",
        documentNumber: "SIM-A-55910244",
        expiryDate: "2028-09-28",
        isRequired: true,
        verificationStatus: "VERIFIED",
      },
    ],
    agreements: [],
  },

  // 5. BLACKLISTED Customer (Unpaid + fraud attempt)
  {
    id: "CUST-005",
    type: "INDIVIDUAL",
    name: "Dian Anggraini",
    nik: "3174064501900003",
    phone: "+62 813-7722-9911",
    email: "dian.anggraini@outlook.com",
    dateOfBirth: "1990-01-15",
    address: "Pondok Indah Bukit Hijau Blok PA-12",
    city: "Jakarta Selatan",
    province: "DKI Jakarta",
    status: "BLACKLISTED",
    joinedDate: "2024-01-20",
    totalRentalsCount: 4,
    activeRentalsCount: 0,
    isBlacklisted: true,
    blacklistReason: "Membawa unit ke luar pulau tanpa izin resmi dan menunggak pembayaran sewa 45 hari.",
    hasUnpaidInvoices: true,
    drivingInfo: {
      licenseNumber: "SIM-A-66190241",
      licenseType: "SIM_A",
      licenseExpiry: "2028-01-15",
      verificationStatus: "VERIFIED",
    },
    emergencyContact: {
      name: "Riko Anggraini",
      relationship: "FAMILY",
      phone: "+62 813-7722-0000",
    },
    documents: [
      {
        id: "DOC-CUST005-KTP",
        documentType: "KTP",
        documentName: "KTP Elektronik",
        documentNumber: "3174064501900003",
        isRequired: true,
        verificationStatus: "VERIFIED",
      },
      {
        id: "DOC-CUST005-SIM",
        documentType: "SIM",
        documentName: "Surat Izin Mengemudi (SIM A)",
        documentNumber: "SIM-A-66190241",
        expiryDate: "2028-01-15",
        isRequired: true,
        verificationStatus: "VERIFIED",
      },
    ],
    agreements: [],
  },
];

export const mockCorporateCustomers: CorporateCustomer[] = [
  // 1. Fully ELIGIBLE ACTIVE Corporate Customer (All B2B documents verified + MSA v2.0 accepted)
  {
    id: "CORP-001",
    type: "CORPORATE",
    name: "PT ABC Indonesia",
    companyInfo: {
      name: "PT ABC Indonesia",
      legalName: "PT ABC Indonesia Tbk",
      entityType: "PT",
      npwp: "01.234.567.8-012.000",
      nib: "9120003410982",
      address: "Sudirman Central Business District (SCBD) Lot 8, Tower One Lt. 25",
      city: "Jakarta Selatan",
      province: "DKI Jakarta",
      postalCode: "12190",
      website: "https://abc-indonesia.co.id",
      industry: "Consumer Goods & FMCG",
    },
    pic: {
      name: "Andi Wijaya",
      role: "Head of General Affairs & Fleet",
      phone: "+62 811-9823-110",
      email: "andi.wijaya@abc-indonesia.co.id",
      idCardNumber: "3174051203800001",
      powerOfAttorneyRef: "SK/DIR/ABC/2024/008",
    },
    billingInfo: {
      billingContactName: "Finance AP Department",
      billingEmail: "ap-billing@abc-indonesia.co.id",
      billingPhone: "+62 21-515-8899",
      billingAddress: "SCBD Lot 8, Tower One Lt. 25, Jakarta Selatan",
      billingNpwp: "01.234.567.8-012.000",
      paymentTermDays: 30,
      bankAccountName: "PT ABC Indonesia",
      bankAccountNumber: "008-129-8833",
      bankName: "Bank Mandiri",
    },
    status: "ACTIVE",
    joinedDate: "2024-01-15",
    activeContractsCount: 2,
    totalAllocatedVehicles: 10,
    operationalVehicles: 9,
    maintenanceVehicles: 1,
    documents: [
      {
        id: "DOC-CORP001-NIB",
        documentType: "NIB",
        documentName: "Nomor Induk Berusaha (NIB)",
        documentNumber: "9120003410982",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Legal Ops Jaja",
        verifiedDate: "2024-01-15",
        fileName: "NIB_PT_ABC_Indonesia.pdf",
      },
      {
        id: "DOC-CORP001-NPWP",
        documentType: "NPWP",
        documentName: "NPWP Badan Usaha",
        documentNumber: "01.234.567.8-012.000",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Legal Ops Jaja",
        verifiedDate: "2024-01-15",
        fileName: "NPWP_Badan_ABC.pdf",
      },
      {
        id: "DOC-CORP001-AKTA",
        documentType: "AKTA_PENDIRIAN",
        documentName: "Akta Pendirian & Kemenkumham",
        documentNumber: "AHU-0019283.AH.01.01.2018",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Legal Ops Jaja",
        verifiedDate: "2024-01-15",
        fileName: "Akta_Pendirian_ABC.pdf",
      },
      {
        id: "DOC-CORP001-KTPPIC",
        documentType: "KTP_PIC",
        documentName: "KTP PIC Pengurus",
        documentNumber: "3174051203800001",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Legal Ops Jaja",
        verifiedDate: "2024-01-15",
        fileName: "KTP_PIC_Andi.jpg",
      },
    ],
    agreements: [
      {
        id: "ACC-CORP-2026-001",
        customerId: "CORP-001",
        agreementId: "AGR-B2B-V2.0",
        agreementType: "B2B_MASTER_SERVICE_AGREEMENT",
        agreementVersion: "2.0",
        acceptedAt: "2026-08-01T09:00:00Z",
        acceptedBy: "Andi Wijaya",
        acceptedByRole: "Head of General Affairs & Procurement (Power of Attorney)",
        acceptedByPhone: "+62 811-9823-110",
        acceptedByEmail: "andi.wijaya@abc-indonesia.co.id",
        ipAddress: "202.158.45.10",
        status: "ACCEPTED",
        acceptedClauses: [
          "CLAUSE-B2B-01",
          "CLAUSE-B2B-02",
          "CLAUSE-B2B-03",
          "CLAUSE-B2B-04",
          "CLAUSE-B2B-05",
        ],
        digitalConsentNote: "Ditandatangani secara digital via Corporate Portal Jaja Rent.",
      },
    ],
  },

  // 2. APPROVED Corporate Customer (Awaiting MSA v2.0 Signature)
  {
    id: "CORP-002",
    type: "CORPORATE",
    name: "PT Maju Bersama",
    companyInfo: {
      name: "PT Maju Bersama",
      legalName: "PT Maju Bersama Manufaktur",
      entityType: "PT",
      npwp: "02.345.678.9-023.000",
      nib: "8120001122334",
      address: "Kawasan Industri MM2100 Blok C-4",
      city: "Bekasi",
      province: "Jawa Barat",
      postalCode: "17530",
      industry: "Manufacturing & Electronics",
    },
    pic: {
      name: "Bambang Sudiro",
      role: "Operations Manager",
      phone: "+62 812-3344-5566",
      email: "bambang.s@majubersama.com",
    },
    billingInfo: {
      billingContactName: "Finance Dept",
      billingEmail: "finance@majubersama.com",
      billingPhone: "+62 21-898-1122",
      billingAddress: "Kawasan Industri MM2100 Blok C-4, Cikarang",
      paymentTermDays: 30,
    },
    status: "APPROVED",
    joinedDate: "2024-03-10",
    activeContractsCount: 1,
    totalAllocatedVehicles: 8,
    operationalVehicles: 8,
    maintenanceVehicles: 0,
    documents: [
      {
        id: "DOC-CORP002-NIB",
        documentType: "NIB",
        documentName: "Nomor Induk Berusaha (NIB)",
        documentNumber: "8120001122334",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Legal Ops Jaja",
        verifiedDate: "2024-03-10",
      },
      {
        id: "DOC-CORP002-NPWP",
        documentType: "NPWP",
        documentName: "NPWP Badan Usaha",
        documentNumber: "02.345.678.9-023.000",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Legal Ops Jaja",
        verifiedDate: "2024-03-10",
      },
      {
        id: "DOC-CORP002-AKTA",
        documentType: "AKTA_PENDIRIAN",
        documentName: "Akta Pendirian",
        documentNumber: "AHU-0033112.AH.01.01.2020",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Legal Ops Jaja",
        verifiedDate: "2024-03-10",
      },
      {
        id: "DOC-CORP002-KTPPIC",
        documentType: "KTP_PIC",
        documentName: "KTP PIC",
        documentNumber: "3275011904790002",
        isRequired: true,
        verificationStatus: "VERIFIED",
        verifiedBy: "Legal Ops Jaja",
        verifiedDate: "2024-03-10",
      },
    ],
    agreements: [], // Chưa ký MSA v2.0!
  },

  // 3. DOCUMENT_REVIEW Stage Corporate
  {
    id: "CORP-003",
    type: "CORPORATE",
    name: "PT Nusantara Logistik",
    companyInfo: {
      name: "PT Nusantara Logistik",
      legalName: "PT Nusantara Logistik Kargo",
      entityType: "PT",
      npwp: "03.456.789.0-034.000",
      nib: "7120004455667",
      address: "Area Kargo Bandara Soekarno-Hatta Building 300",
      city: "Tangerang",
      province: "Banten",
      industry: "Logistics & Freight Forwarding",
    },
    pic: {
      name: "Fajar Nugraha",
      role: "Logistics Director",
      phone: "+62 813-8899-7711",
      email: "fajar.nugraha@nusantaralogistik.id",
    },
    billingInfo: {
      billingContactName: "Accounting Lead",
      billingEmail: "accounting@nusantaralogistik.id",
      billingPhone: "+62 21-550-9900",
      billingAddress: "Area Kargo Bandara Soetta Building 300",
      paymentTermDays: 45,
    },
    status: "DOCUMENT_REVIEW",
    joinedDate: "2026-08-30",
    activeContractsCount: 0,
    totalAllocatedVehicles: 0,
    operationalVehicles: 0,
    maintenanceVehicles: 0,
    documents: [
      {
        id: "DOC-CORP003-NIB",
        documentType: "NIB",
        documentName: "Nomor Induk Berusaha (NIB)",
        documentNumber: "7120004455667",
        isRequired: true,
        verificationStatus: "PENDING",
      },
      {
        id: "DOC-CORP003-NPWP",
        documentType: "NPWP",
        documentName: "NPWP Badan Usaha",
        documentNumber: "03.456.789.0-034.000",
        isRequired: true,
        verificationStatus: "PENDING",
      },
      {
        id: "DOC-CORP003-AKTA",
        documentType: "AKTA_PENDIRIAN",
        documentName: "Akta Pendirian",
        documentNumber: "AHU-0077889.AH.01.01.2021",
        isRequired: true,
        verificationStatus: "PENDING",
      },
      {
        id: "DOC-CORP003-KTPPIC",
        documentType: "KTP_PIC",
        documentName: "KTP PIC",
        documentNumber: "3671021805820001",
        isRequired: true,
        verificationStatus: "PENDING",
      },
    ],
    agreements: [],
  },

  // 4. SUSPENDED Corporate Customer (Overdue unpaid billing)
  {
    id: "CORP-004",
    type: "CORPORATE",
    name: "PT Sinar Abadi",
    companyInfo: {
      name: "PT Sinar Abadi",
      legalName: "PT Sinar Abadi Distribusi",
      entityType: "PT",
      npwp: "04.567.890.1-045.000",
      nib: "6120009988776",
      address: "Jl. R.E. Martadinata No. 128",
      city: "Bandung",
      province: "Jawa Barat",
      industry: "Retail & Distribution",
    },
    pic: {
      name: "Rina Kusuma",
      role: "Procurement Lead",
      phone: "+62 818-0928-3412",
      email: "rina.k@sinarabadi.co.id",
    },
    billingInfo: {
      billingContactName: "Finance AP",
      billingEmail: "finance@sinarabadi.co.id",
      billingPhone: "+62 22-420-1122",
      billingAddress: "Jl. R.E. Martadinata No. 128, Bandung",
      paymentTermDays: 30,
    },
    status: "SUSPENDED",
    joinedDate: "2024-05-01",
    hasUnpaidInvoices: true,
    activeContractsCount: 1,
    totalAllocatedVehicles: 6,
    operationalVehicles: 6,
    maintenanceVehicles: 0,
    documents: [
      {
        id: "DOC-CORP004-NIB",
        documentType: "NIB",
        documentName: "Nomor Induk Berusaha (NIB)",
        documentNumber: "6120009988776",
        isRequired: true,
        verificationStatus: "VERIFIED",
      },
      {
        id: "DOC-CORP004-NPWP",
        documentType: "NPWP",
        documentName: "NPWP Badan Usaha",
        documentNumber: "04.567.890.1-045.000",
        isRequired: true,
        verificationStatus: "VERIFIED",
      },
      {
        id: "DOC-CORP004-AKTA",
        documentType: "AKTA_PENDIRIAN",
        documentName: "Akta Pendirian",
        documentNumber: "AHU-0012399.AH.01.01.2019",
        isRequired: true,
        verificationStatus: "VERIFIED",
      },
      {
        id: "DOC-CORP004-KTPPIC",
        documentType: "KTP_PIC",
        documentName: "KTP PIC",
        documentNumber: "3273014506890003",
        isRequired: true,
        verificationStatus: "VERIFIED",
      },
    ],
    agreements: [
      {
        id: "ACC-CORP-2025-012",
        customerId: "CORP-004",
        agreementId: "AGR-B2B-V2.0",
        agreementType: "B2B_MASTER_SERVICE_AGREEMENT",
        agreementVersion: "2.0",
        acceptedAt: "2026-08-01T10:00:00Z",
        acceptedBy: "Rina Kusuma",
        ipAddress: "180.252.19.88",
        status: "ACCEPTED",
        acceptedClauses: ["CLAUSE-B2B-01", "CLAUSE-B2B-02", "CLAUSE-B2B-03", "CLAUSE-B2B-04", "CLAUSE-B2B-05"],
      },
    ],
  },
];
