import { CorporateCustomer } from "../types/corporate";

export const mockCorporateCustomers: CorporateCustomer[] = [
  {
    id: "CORP-001",
    name: "PT ABC Indonesia",
    industry: "Consumer Goods & FMCG",
    address: "Sudirman Central Business District (SCBD) Lot 8",
    city: "Jakarta Selatan",
    picName: "Andi Wijaya",
    picRole: "Head of General Affairs & Fleet",
    picPhone: "+62 811-9823-110",
    picEmail: "andi.wijaya@abc-indonesia.co.id",
    activeContractsCount: 2,
    totalAllocatedVehicles: 10,
    operationalVehicles: 9,
    maintenanceVehicles: 1,
    status: "ACTIVE",
    joinedDate: "2024-01-15",
  },
  {
    id: "CORP-002",
    name: "PT Maju Bersama",
    industry: "Manufacturing & Electronics",
    address: "Kawasan Industri MM2100 Blok C-4",
    city: "Bekasi",
    picName: "Bambang Sudiro",
    picRole: "Operations Manager",
    picPhone: "+62 812-3344-5566",
    picEmail: "bambang.s@majubersama.com",
    activeContractsCount: 1,
    totalAllocatedVehicles: 8,
    operationalVehicles: 8,
    maintenanceVehicles: 0,
    status: "ACTIVE",
    joinedDate: "2024-03-10",
  },
  {
    id: "CORP-003",
    name: "PT Nusantara Logistik",
    industry: "Logistics & Freight Forwarding",
    address: "Area Kargo Bandara Soekarno-Hatta Building 300",
    city: "Tangerang",
    picName: "Fajar Nugraha",
    picRole: "Logistics Director",
    picPhone: "+62 813-8899-7711",
    picEmail: "fajar.nugraha@nusantaralogistik.id",
    activeContractsCount: 2,
    totalAllocatedVehicles: 15,
    operationalVehicles: 14,
    maintenanceVehicles: 1,
    status: "ACTIVE",
    joinedDate: "2023-11-20",
  },
  {
    id: "CORP-004",
    name: "PT Sinar Abadi",
    industry: "Retail & Distribution",
    address: "Jl. R.E. Martadinata No. 128",
    city: "Bandung",
    picName: "Rina Kusuma",
    picRole: "Procurement Lead",
    picPhone: "+62 818-0928-3412",
    picEmail: "rina.k@sinarabadi.co.id",
    activeContractsCount: 1,
    totalAllocatedVehicles: 6,
    operationalVehicles: 6,
    maintenanceVehicles: 0,
    status: "ACTIVE",
    joinedDate: "2024-05-01",
  },
  {
    id: "CORP-005",
    name: "PT Mandiri Distribusi",
    industry: "Supply Chain & Warehousing",
    address: "Jl. Yos Sudarso No. 88, Tanjung Priok",
    city: "Jakarta Utara",
    picName: "Hendro Gunawan",
    picRole: "Fleet Coordinator",
    picPhone: "+62 811-2399-440",
    picEmail: "h.gunawan@mandiridistribusi.com",
    activeContractsCount: 1,
    totalAllocatedVehicles: 12,
    operationalVehicles: 12,
    maintenanceVehicles: 0,
    status: "ACTIVE",
    joinedDate: "2024-02-18",
  },
  {
    id: "CORP-006",
    name: "PT Astra Surya",
    industry: "Financial Technology",
    address: "Menara Astra Lt. 32, Jl. Jend. Sudirman Kav. 5-6",
    city: "Jakarta Pusat",
    picName: "Siti Rahmawati",
    picRole: "General Services Lead",
    picPhone: "+62 812-7711-2299",
    picEmail: "siti.rahma@astrasurya.co.id",
    activeContractsCount: 1,
    totalAllocatedVehicles: 5,
    operationalVehicles: 5,
    maintenanceVehicles: 0,
    status: "ACTIVE",
    joinedDate: "2024-06-15",
  },
  {
    id: "CORP-007",
    name: "PT Graha Finansial",
    industry: "Banking & Securities",
    address: "World Trade Center 3, Jl. Jend. Sudirman",
    city: "Jakarta Selatan",
    picName: "Denny Pradana",
    picRole: "VP Corporate Support",
    picPhone: "+62 815-9928-1122",
    picEmail: "denny.pradana@grahafinansial.com",
    activeContractsCount: 1,
    totalAllocatedVehicles: 7,
    operationalVehicles: 7,
    maintenanceVehicles: 0,
    status: "ACTIVE",
    joinedDate: "2023-09-01",
  },
  {
    id: "CORP-008",
    name: "PT Mega Konstruksi",
    industry: "Infrastructure & Heavy Engineering",
    address: "Jl. TB Simatupang No. 18, Cilandak",
    city: "Jakarta Selatan",
    picName: "Agus Pratama",
    picRole: "Project Logistics Manager",
    picPhone: "+62 812-8811-9933",
    picEmail: "agus.pratama@megakonstruksi.id",
    activeContractsCount: 1,
    totalAllocatedVehicles: 9,
    operationalVehicles: 9,
    maintenanceVehicles: 0,
    status: "ACTIVE",
    joinedDate: "2024-04-12",
  },
  {
    id: "CORP-009",
    name: "PT Mitra Solusindo",
    industry: "IT & Telecommunications",
    address: "Cyber 2 Tower Lt. 19, Jl. HR Rasuna Said",
    city: "Jakarta Selatan",
    picName: "Vina Mariska",
    picRole: "HR & Admin Supervisor",
    picPhone: "+62 817-4488-9900",
    picEmail: "vina.m@mitrasolusindo.com",
    activeContractsCount: 1,
    totalAllocatedVehicles: 4,
    operationalVehicles: 4,
    maintenanceVehicles: 0,
    status: "ACTIVE",
    joinedDate: "2024-07-20",
  },
  {
    id: "CORP-010",
    name: "PT Bahtera Eka",
    industry: "Energy & Marine Shipping",
    address: "Jl. Danau Sunter Utara Blok F No. 12",
    city: "Jakarta Utara",
    picName: "Lukman Hakim",
    picRole: "Operations Lead",
    picPhone: "+62 813-1122-3344",
    picEmail: "lukman.hakim@bahteraeka.co.id",
    activeContractsCount: 1,
    totalAllocatedVehicles: 6,
    operationalVehicles: 6,
    maintenanceVehicles: 0,
    status: "ACTIVE",
    joinedDate: "2024-08-01",
  },
];
