import { GPSTelemetry } from "../types/operations";

export const mockGPSTelemetry: GPSTelemetry[] = [
  {
    vehicleId: "B-1234-XYZ",
    plateNumber: "B 1234 XYZ",
    model: "Toyota Innova Zenix 2.0 V",
    customerName: "PT ABC Indonesia",
    businessType: "B2B",
    status: "ONLINE",
    latitude: -6.2255,
    longitude: 106.8095,
    address: "SCBD Lot 8, Jl. Jend. Sudirman Kav. 52-53",
    city: "Jakarta Selatan",
    speed: 38,
    heading: "NE",
    odometer: 82421,
    batteryLevel: 98,
    ignition: "ON",
    lastUpdate: "2 min ago",
    rentalStatus: "RENTED",
  },
  {
    vehicleId: "B-5678-ABC",
    plateNumber: "B 5678 ABC",
    model: "Toyota Veloz 1.5 Q CVT",
    businessType: "UNASSIGNED",
    status: "ONLINE",
    latitude: -6.1754,
    longitude: 106.7725,
    address: "Pool Kebon Jeruk, Jl. Panjang No. 12",
    city: "Jakarta Barat",
    speed: 0,
    heading: "N",
    odometer: 45210,
    batteryLevel: 100,
    ignition: "OFF",
    lastUpdate: "Just now",
    rentalStatus: "AVAILABLE",
  },
  {
    vehicleId: "B-2345-DEF",
    plateNumber: "B 2345 DEF",
    model: "Toyota Fortuner 2.8 GR Sport",
    customerName: "Hendrawan Putra",
    businessType: "B2C",
    status: "ONLINE",
    latitude: -6.1952,
    longitude: 106.8217,
    address: "Jl. M.H. Thamrin No. 1, Grand Indonesia",
    city: "Jakarta Pusat",
    speed: 24,
    heading: "SE",
    odometer: 31050,
    batteryLevel: 94,
    ignition: "ON",
    lastUpdate: "4 min ago",
    rentalStatus: "RENTED",
  },
  {
    vehicleId: "B-8899-KLU",
    plateNumber: "B 8899 KLU",
    model: "Mitsubishi Xpander Ultimate",
    customerName: "PT ABC Indonesia",
    businessType: "B2B",
    status: "IDLE",
    latitude: -6.1932,
    longitude: 106.9012,
    address: "Bengkel AutoCare, Jl. Pemuda Pulogadung",
    city: "Jakarta Timur",
    speed: 0,
    heading: "E",
    odometer: 58920,
    batteryLevel: 88,
    ignition: "OFF",
    lastUpdate: "1 hr ago",
    rentalStatus: "MAINTENANCE",
  },
  {
    vehicleId: "B-9123-POX",
    plateNumber: "B 9123 POX",
    model: "Toyota HiAce Commuter 2.5",
    customerName: "PT Nusantara Logistik",
    businessType: "B2B",
    status: "ONLINE",
    latitude: -6.1275,
    longitude: 106.6537,
    address: "Area Kargo Bandara Soekarno Hatta",
    city: "Tangerang",
    speed: 45,
    heading: "W",
    odometer: 114500,
    batteryLevel: 95,
    ignition: "ON",
    lastUpdate: "5 min ago",
    rentalStatus: "RENTED",
  },
  {
    vehicleId: "B-3344-ZZA",
    plateNumber: "B 3344 ZZA",
    model: "Hyundai Stargazer Prime",
    businessType: "UNASSIGNED",
    status: "ONLINE",
    latitude: -6.2941,
    longitude: 106.7993,
    address: "Pool Cilandak, Jl. TB Simatupang No. 8",
    city: "Jakarta Selatan",
    speed: 0,
    heading: "S",
    odometer: 28400,
    batteryLevel: 100,
    ignition: "OFF",
    lastUpdate: "10 min ago",
    rentalStatus: "AVAILABLE",
  },
  {
    vehicleId: "B-7711-GHY",
    plateNumber: "B 7711 GHY",
    model: "Honda HR-V 1.5 SE CVT",
    customerName: "Jessica Tanuwidjaja",
    businessType: "B2C",
    status: "ONLINE",
    latitude: -6.3015,
    longitude: 106.6521,
    address: "Green Office Park BSD City",
    city: "Tangerang Selatan",
    speed: 52,
    heading: "SW",
    odometer: 39800,
    batteryLevel: 91,
    ignition: "ON",
    lastUpdate: "1 min ago",
    rentalStatus: "RENTED",
  },
  {
    vehicleId: "B-9988-TYU",
    plateNumber: "B 9988 TYU",
    model: "Daihatsu GranMax Blind Van",
    businessType: "B2B",
    status: "OFFLINE",
    latitude: -6.1554,
    longitude: 106.6781,
    address: "Bengkel Sentosa, Jl. Daan Mogot KM 14",
    city: "Tangerang",
    speed: 0,
    heading: "N",
    odometer: 132000,
    batteryLevel: 0,
    ignition: "OFF",
    lastUpdate: "4 hrs ago",
    rentalStatus: "MAINTENANCE",
  },
];
