import { InspectionRecord } from "../types/operations";

export const mockInspections: InspectionRecord[] = [
  {
    id: "INSP-2026-0901",
    vehicleId: "B-1234-XYZ",
    plateNumber: "B 1234 XYZ",
    model: "Toyota Innova Zenix 2.0 V",
    type: "PERIODIC",
    date: "2026-09-01",
    odometer: 82421,
    inspectorName: "Ahmad Subarjo",
    result: "PASSED",
    checklist: {
      exterior: { body: true, glass: true, tire: true, lamp: true },
      interior: { seat: true, ac: true, dashboard: true, cleanliness: true },
      engine: { oil: true, coolant: true, battery: true, brakeFluid: true },
      safety: { seatbelt: true, airbag: true, spareTire: true, toolKit: true },
    },
    notes:
      "Unit in pristine operational condition. Hybrid battery cooling intake clean.",
  },
  {
    id: "INSP-2026-0828",
    vehicleId: "B-1099-QWE",
    plateNumber: "B 1099 QWE",
    model: "Hyundai Ioniq 5 Signature",
    type: "PERIODIC",
    date: "2026-08-28",
    odometer: 18450,
    inspectorName: "Bayu Wicaksono",
    result: "PENDING",
    checklist: {
      exterior: { body: true, glass: true, tire: false, lamp: true },
      interior: { seat: true, ac: true, dashboard: true, cleanliness: true },
      engine: { oil: true, coolant: true, battery: true, brakeFluid: true },
      safety: { seatbelt: true, airbag: true, spareTire: true, toolKit: true },
    },
    notes:
      "Rear left tire tread depth 2.1mm. Recommended tire rotation before returning to available fleet.",
    issuesFound: ["Tire tread low on rear left"],
  },
  {
    id: "INSP-2026-0825",
    vehicleId: "B-8899-KLU",
    plateNumber: "B 8899 KLU",
    model: "Mitsubishi Xpander Ultimate",
    type: "INCIDENT",
    date: "2026-08-25",
    odometer: 58920,
    inspectorName: "Ahmad Subarjo",
    result: "FAILED",
    checklist: {
      exterior: { body: false, glass: true, tire: true, lamp: true },
      interior: { seat: true, ac: true, dashboard: true, cleanliness: true },
      engine: { oil: true, coolant: true, battery: true, brakeFluid: false },
      safety: { seatbelt: true, airbag: true, spareTire: true, toolKit: true },
    },
    notes:
      "Brake pulsation detected during road test and minor rear bumper scuff. Dispatched to AutoCare Pulogadung.",
    issuesFound: [
      "Front brake rotor warped",
      "Brake fluid degradation",
      "Rear bumper scratch",
    ],
  },
  {
    id: "INSP-2026-0820",
    vehicleId: "B-5678-ABC",
    plateNumber: "B 5678 ABC",
    model: "Toyota Veloz 1.5 Q CVT",
    type: "POST_RENTAL",
    date: "2026-08-20",
    odometer: 45210,
    inspectorName: "Dedi Setiawan",
    result: "PASSED",
    checklist: {
      exterior: { body: true, glass: true, tire: true, lamp: true },
      interior: { seat: true, ac: true, dashboard: true, cleanliness: true },
      engine: { oil: true, coolant: true, battery: true, brakeFluid: true },
      safety: { seatbelt: true, airbag: true, spareTire: true, toolKit: true },
    },
    notes: "Returned on schedule. Deep interior detail completed.",
  },
  {
    id: "INSP-2026-0815",
    vehicleId: "B-2345-DEF",
    plateNumber: "B 2345 DEF",
    model: "Toyota Fortuner 2.8 GR Sport",
    type: "PRE_RENTAL",
    date: "2026-08-15",
    odometer: 30800,
    inspectorName: "Ahmad Subarjo",
    result: "PASSED",
    checklist: {
      exterior: { body: true, glass: true, tire: true, lamp: true },
      interior: { seat: true, ac: true, dashboard: true, cleanliness: true },
      engine: { oil: true, coolant: true, battery: true, brakeFluid: true },
      safety: { seatbelt: true, airbag: true, spareTire: true, toolKit: true },
    },
    notes:
      "All 4x4 electronic lockers tested and working. Prepared for VIP rental.",
  },
];
