import { MaintenanceRecord } from "../types/operations";

export const mockMaintenance: MaintenanceRecord[] = [
  {
    id: "MNT-2026-0810",
    vehicleId: "B-1234-XYZ",
    plateNumber: "B 1234 XYZ",
    model: "Toyota Innova Zenix 2.0 V CVT",
    type: "PERIODIC_SERVICE",
    date: "2026-08-10",
    odometer: 80000,
    workshopName: "AutoCare Pulogadung",
    workshopLocation: "Jl. Pemuda No. 81, Jakarta Timur",
    cost: 2500000,
    status: "COMPLETED",
    description:
      "Major 80,000 KM Periodic Service, Engine Oil 0W-20 Full Synthetic, Spark Plugs replacement, Transaxle Oil inspection.",
    partsReplaced: [
      "Engine Oil 0W-20",
      "Oil Filter",
      "Cabin Air Filter",
      "Iridium Spark Plugs",
    ],
    durationDays: 1,
  },
  {
    id: "MNT-2026-0826",
    vehicleId: "B-8899-KLU",
    plateNumber: "B 8899 KLU",
    model: "Mitsubishi Xpander Ultimate",
    type: "REPAIR",
    date: "2026-08-26",
    odometer: 58920,
    workshopName: "AutoCare Pulogadung",
    workshopLocation: "Jl. Pemuda No. 81, Jakarta Timur",
    cost: 4850000,
    status: "IN_PROGRESS",
    description:
      "Front brake disc replacement, brake pad OEM, brake caliper sliding pin lubrication, and rear bumper spot repainting.",
    partsReplaced: [
      "Front Disc Rotors (Pair)",
      "OEM Ceramic Brake Pads",
      "DOT4 Brake Fluid",
    ],
    durationDays: 4,
  },
  {
    id: "MNT-2026-0827",
    vehicleId: "B-9988-TYU",
    plateNumber: "B 9988 TYU",
    model: "Daihatsu GranMax Blind Van 1.3",
    type: "REPAIR",
    date: "2026-08-27",
    odometer: 132000,
    workshopName: "Bengkel Sentosa Daan Mogot",
    workshopLocation: "Jl. Daan Mogot KM 14, Tangerang",
    cost: 3200000,
    status: "IN_PROGRESS",
    description:
      "Clutch plate set replacement (Clutch Disc, Cover, Release Bearing) & alternator belt tightening.",
    partsReplaced: [
      "Clutch Disc",
      "Clutch Cover",
      "Release Bearing",
      "Fan Belt",
    ],
    durationDays: 3,
  },
  {
    id: "MNT-2026-0718",
    vehicleId: "B-5678-ABC",
    plateNumber: "B 5678 ABC",
    model: "Toyota Veloz 1.5 Q CVT",
    type: "PERIODIC_SERVICE",
    date: "2026-07-18",
    odometer: 40000,
    workshopName: "Plaza Toyota Kebon Jeruk",
    workshopLocation: "Jl. Panjang No. 33, Jakarta Barat",
    cost: 1850000,
    status: "COMPLETED",
    description:
      "40,000 KM Periodic Service & 4-wheel computerized balancing alignment.",
    partsReplaced: ["Toyota Motor Oil 0W-16", "Oil Filter", "Gasket Plug"],
    durationDays: 1,
  },
  {
    id: "MNT-2026-0705",
    vehicleId: "B-4422-RST",
    plateNumber: "B 4422 RST",
    model: "Toyota Innova Reborn 2.4 G Diesel",
    type: "PERIODIC_SERVICE",
    date: "2026-07-05",
    odometer: 90000,
    workshopName: "Auto2000 Cikarang",
    workshopLocation: "Jl. MH Thamrin Kav 128, Cikarang",
    cost: 2900000,
    status: "COMPLETED",
    description:
      "90,000 KM Diesel Service, Fuel Filter replacement & EGR clean.",
    partsReplaced: [
      "Diesel Fuel Filter",
      "Synthetic Diesel Oil 5W-30",
      "Oil Filter",
    ],
    durationDays: 1,
  },
];
