/**
 * ==============================================================================
 * Phase 2: Fleet Operations Seed Data
 * ==============================================================================
 */

import type { Vehicle } from "../types/fleet.ts";
import type {
  VehicleAllocationRecord,
  VehicleDamageRecord,
  InspectionConditionItem,
  MaintenanceItemizedRecord,
  MaintenanceQCRecord,
  VehicleDocumentWithAlert,
  GPSTelematicsInfo,
  VehicleTimelineEvent,
} from "../types/fleet-operations.ts";

/**
 * 1. Comprehensive Seed Fleet (All operational & lifecycle statuses)
 */
export const phase2SeedVehicles: Vehicle[] = [
  {
    id: "B-1234-XYZ",
    plateNumber: "B 1234 XYZ",
    brand: "Toyota",
    model: "Innova Zenix 2.0 V CVT",
    year: 2024,
    color: "Platinum White Pearl",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHFXW43G6R0129841",
    engineNumber: "M20A-FKS-993821",
    status: "AVAILABLE",
    lifecycleStatus: "ACTIVE",
    lifecycleStage: "AVAILABLE",
    businessEligibility: "BOTH",
    ownership: "JAJA_OWNED",
    odometer: 14500,
    locationCity: "Jakarta Selatan",
    locationArea: "SCBD Lot 8",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "Baru saja",
    latitude: -6.2255,
    longitude: 106.8095,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 20000,
    dailyRateB2C: 650000,
    monthlyRateB2B: 14500000,
  },
  {
    id: "B-5678-ABC",
    plateNumber: "B 5678 ABC",
    brand: "Toyota",
    model: "Fortuner 2.8 GR Sport 4x4",
    year: 2024,
    color: "Attitude Black Mica",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatCapacity: 7,
    vin: "MHFZ781A8P0031892",
    engineNumber: "1GD-FTV-882194",
    status: "ALLOCATED",
    lifecycleStatus: "ACTIVE",
    lifecycleStage: "RESERVED",
    businessEligibility: "BOTH",
    ownership: "JAJA_OWNED",
    odometer: 28400,
    locationCity: "Jakarta Pusat",
    locationArea: "Gambir Hub",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "5 menit lalu",
    latitude: -6.1754,
    longitude: 106.8272,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 30000,
    dailyRateB2C: 1100000,
    monthlyRateB2B: 24000000,
    currentAllocationId: "ALC-10002",
  },
  {
    id: "B-9012-DEF",
    plateNumber: "B 9012 DEF",
    brand: "Toyota",
    model: "Avanza 1.5 G CVT TSS",
    year: 2023,
    color: "Silver Mica Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHFZ781A8P0099411",
    engineNumber: "2NR-VE-449102",
    status: "RENTED",
    lifecycleStatus: "ACTIVE",
    lifecycleStage: "RENTED",
    businessEligibility: "BOTH",
    ownership: "JAJA_OWNED",
    odometer: 42100,
    currentCustomerName: "Faisal Nugraha",
    currentRentalId: "RNT-B2C-2026-001",
    locationCity: "Jakarta Timur",
    locationArea: "Pulogadung Depot",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "1 menit lalu",
    latitude: -6.1954,
    longitude: 106.9023,
    speed: 38,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 50000,
    dailyRateB2C: 450000,
    monthlyRateB2B: 8500000,
  },
  {
    id: "B-2345-GHI",
    plateNumber: "B 2345 GHI",
    brand: "Mitsubishi",
    model: "Pajero Sport 2.4 Dakar Ultimate",
    year: 2023,
    color: "Deep Bronze Metallic",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatCapacity: 7,
    vin: "MMBFU81A7P0088192",
    engineNumber: "4N15-U778102",
    status: "INSPECTION",
    lifecycleStatus: "ACTIVE",
    lifecycleStage: "INSPECTION",
    businessEligibility: "BOTH",
    ownership: "JAJA_OWNED",
    odometer: 35800,
    locationCity: "Jakarta Selatan",
    locationArea: "Pool TB Simatupang",
    gpsStatus: "IDLE",
    lastGpsUpdate: "20 menit lalu",
    latitude: -6.2954,
    longitude: 106.8123,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "DUE",
    nextServiceOdometer: 35000, // Service overdue by 800 km
    dailyRateB2C: 1050000,
    monthlyRateB2B: 23000000,
  },
  {
    id: "B-6789-JKL",
    plateNumber: "B 6789 JKL",
    brand: "Honda",
    model: "HR-V 1.5 SE CVT",
    year: 2023,
    color: "Ignite Red Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 5,
    vin: "MRHRV81A6P0011928",
    engineNumber: "L15ZF-990182",
    status: "MAINTENANCE",
    lifecycleStatus: "ACTIVE",
    lifecycleStage: "MAINTENANCE",
    businessEligibility: "B2C",
    ownership: "JAJA_OWNED",
    odometer: 29900,
    locationCity: "Jakarta Barat",
    locationArea: "Bengkel Resmi Honda Kebon Jeruk",
    gpsStatus: "OFFLINE",
    lastGpsUpdate: "3 jam lalu (Bengkel)",
    latitude: -6.1854,
    longitude: 106.7723,
    speed: 0,
    documentStatus: "EXPIRING_SOON", // STNK expiring in 15 days
    maintenanceStatus: "IN_PROGRESS",
    nextServiceOdometer: 30000,
    dailyRateB2C: 550000,
  },
  {
    id: "B-7890-MNO",
    plateNumber: "B 7890 MNO",
    brand: "Toyota",
    model: "HiAce Premio 2.8 MT",
    year: 2022,
    color: "Silver Metallic",
    transmission: "Manual",
    fuelType: "Diesel",
    seatCapacity: 14,
    vin: "MHFXH81A5P0019283",
    engineNumber: "1GD-FTV-771923",
    status: "DOCUMENT_HOLD",
    lifecycleStatus: "ACTIVE",
    lifecycleStage: "PROBLEM",
    businessEligibility: "BOTH",
    ownership: "JAJA_OWNED",
    odometer: 68400,
    locationCity: "Jakarta Utara",
    locationArea: "Pool Tanjung Priok",
    gpsStatus: "IDLE",
    lastGpsUpdate: "45 menit lalu",
    latitude: -6.1254,
    longitude: 106.8823,
    speed: 0,
    documentStatus: "EXPIRED", // KIR expired!
    maintenanceStatus: "OK",
    nextServiceOdometer: 70000,
    dailyRateB2C: 1300000,
    monthlyRateB2B: 26000000,
  },
];

/**
 * 2. Seed Allocations
 */
export const phase2SeedAllocations: VehicleAllocationRecord[] = [
  {
    id: "ALC-10001",
    allocationNumber: "ALC-10001",
    vehicleId: "B-1234-XYZ",
    vehiclePlate: "B 1234 XYZ",
    vehicleModel: "Toyota Innova Zenix 2.0 V CVT",
    reservationId: "RES-000002",
    reservationNumber: "RES-000002",
    rentalId: "RNT-000002",
    startAt: "2026-09-15",
    endAt: "2026-09-18",
    status: "ALLOCATED",
    allocatedBy: "Ops Specialist Rudi",
    allocatedAt: "2026-09-02T10:00:00Z",
  },
  {
    id: "ALC-10002",
    allocationNumber: "ALC-10002",
    vehicleId: "B-5678-ABC",
    vehiclePlate: "B 5678 ABC",
    vehicleModel: "Toyota Fortuner 2.8 GR Sport 4x4",
    reservationId: "RES-000003",
    reservationNumber: "RES-000003",
    startAt: "2026-09-05",
    endAt: "2026-09-08",
    status: "ALLOCATED",
    allocatedBy: "Ops Dispatcher Dimas",
    allocatedAt: "2026-09-01T14:30:00Z",
  },
];

/**
 * 3. Seed 10-Area Inspection Condition Items (Pre-Rental Baseline)
 */
export const seedPreRentalConditionItems: InspectionConditionItem[] = [
  {
    id: "COND-01",
    area: "BODY",
    componentName: "Bumper Depan & Belakang",
    conditionDescription: "Mulus tanpa baret signifikan",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-02",
    area: "GLASS",
    componentName: "Kaca Depan & Samping",
    conditionDescription: "Bening, tanpa retak",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-03",
    area: "LIGHTS",
    componentName: "Headlamp & Stoplamp LED",
    conditionDescription: "Berfungsi normal, mika jernih",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-04",
    area: "TIRES",
    componentName: "4 Roda + Ban Serep",
    conditionDescription: "Ketebalan ulir 85%, velg mulus",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-05",
    area: "ENGINE",
    componentName: "Mesin & Transmisi CVT",
    conditionDescription: "Kering, tanpa rembesan oli, tarikan halus",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-06",
    area: "INTERIOR",
    componentName: "Jok Kulit & Dashboard",
    conditionDescription: "Bersih, wangi, tidak ada noda",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-07",
    area: "ELECTRICAL",
    componentName: "Headunit & Power Window",
    conditionDescription: "Semua tombol dan layar sentuh responsif",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-08",
    area: "AC",
    componentName: "Sistem AC Dual Zone",
    conditionDescription: "Dingin optimal 20°C, hembusan kencang",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-09",
    area: "SAFETY",
    componentName: "Sabuk Pengaman, Segitiga & APAR",
    conditionDescription: "Lengkap dan masa berlaku APAR aman",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-10",
    area: "OTHER",
    componentName: "Kunci Serep & Toolkit",
    conditionDescription: "Lengkap dalam tas toolkit bagasi",
    severity: "NORMAL",
    isNormal: true,
  },
];

/**
 * 4. Seed Return Inspection Items (With New Defect for comparison testing)
 */
export const seedReturnConditionItems: InspectionConditionItem[] = [
  {
    id: "COND-RET-01",
    area: "BODY",
    componentName: "Bumper Depan & Belakang",
    conditionDescription: "Baret dalam 15 cm pada sudut bemper belakang kiri",
    severity: "MINOR",
    isNormal: false,
    notes: "Terkena tiang pagar saat parkir mundur",
  },
  {
    id: "COND-RET-02",
    area: "GLASS",
    componentName: "Kaca Depan & Samping",
    conditionDescription: "Bening, tanpa retak",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-RET-03",
    area: "LIGHTS",
    componentName: "Headlamp & Stoplamp LED",
    conditionDescription: "Berfungsi normal, mika jernih",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-RET-04",
    area: "TIRES",
    componentName: "4 Roda + Ban Serep",
    conditionDescription: "Ketebalan ulir 83%, velg belakang kiri baret minor",
    severity: "MINOR",
    isNormal: false,
  },
  {
    id: "COND-RET-05",
    area: "ENGINE",
    componentName: "Mesin & Transmisi CVT",
    conditionDescription: "Kering, tanpa rembesan oli, tarikan halus",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-RET-06",
    area: "INTERIOR",
    componentName: "Jok Kulit & Dashboard",
    conditionDescription: "Bersih, sedikit remah makanan di karpet belakang",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-RET-07",
    area: "ELECTRICAL",
    componentName: "Headunit & Power Window",
    conditionDescription: "Semua tombol dan layar sentuh responsif",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-RET-08",
    area: "AC",
    componentName: "Sistem AC Dual Zone",
    conditionDescription: "Dingin optimal 20°C, hembusan kencang",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-RET-09",
    area: "SAFETY",
    componentName: "Sabuk Pengaman, Segitiga & APAR",
    conditionDescription: "Lengkap dan masa berlaku APAR aman",
    severity: "NORMAL",
    isNormal: true,
  },
  {
    id: "COND-RET-10",
    area: "OTHER",
    componentName: "Kunci Serep & Toolkit",
    conditionDescription: "Lengkap dalam tas toolkit bagasi",
    severity: "NORMAL",
    isNormal: true,
  },
];

/**
 * 5. Seed Damage Ledger
 */
export const phase2SeedDamages: VehicleDamageRecord[] = [
  {
    id: "DMG-1001",
    damageNumber: "DMG-1001",
    vehicleId: "B-9012-DEF",
    vehiclePlate: "B 9012 DEF",
    rentalId: "RNT-B2C-2026-001",
    inspectionId: "INSP-RET-001",
    area: "BODY",
    description: "Baret pada bemper samping kanan belakang",
    severity: "MINOR",
    estimatedCost: 250000,
    actualCost: 250000,
    status: "CHARGED",
    reportedAt: "2026-09-03T02:00:00Z",
    notes: "Telah dibebankan dan dipotong dari deposit sewa",
  },
];

/**
 * 6. Seed Maintenance Checklist & Items
 */
export const seedMaintenanceItems: MaintenanceItemizedRecord[] = [
  {
    id: "MNT-ITEM-01",
    category: "OIL",
    itemName: "Oli Mesin Toyota Motor Oil 0W-20 (4 Liter)",
    quantity: 4,
    unitCost: 165000,
    subtotal: 660000,
    status: "REPLACED",
  },
  {
    id: "MNT-ITEM-02",
    category: "ENGINE",
    itemName: "Filter Oli Denso Original",
    quantity: 1,
    unitCost: 85000,
    subtotal: 85000,
    status: "REPLACED",
  },
  {
    id: "MNT-ITEM-03",
    category: "BRAKE",
    itemName: "Brake Pad Depan & Pembersihan Kaliper",
    quantity: 1,
    unitCost: 450000,
    subtotal: 450000,
    status: "REPLACED",
  },
  {
    id: "MNT-ITEM-04",
    category: "OTHER",
    itemName: "Jasa Servis Berkala 30.000 KM & Tune Up",
    quantity: 1,
    unitCost: 350000,
    subtotal: 350000,
    status: "OK",
  },
];

/**
 * 7. Seed Vehicle Legal Documents
 */
export const phase2SeedDocuments: VehicleDocumentWithAlert[] = [
  {
    id: "DOC-STNK-01",
    vehicleId: "B-1234-XYZ",
    documentType: "STNK",
    documentNumber: "0912831/STNK/2024",
    issuedDate: "2024-05-10",
    issueDate: "2024-05-10",
    expiryDate: "2029-05-10",
    daysUntilExpiry: 980,
    alertStatus: "VALID",
    costToRenew: 3850000,
  },
  {
    id: "DOC-KIR-01",
    vehicleId: "B-7890-MNO",
    documentType: "KIR",
    documentNumber: "KIR-DKI-99210",
    issuedDate: "2025-08-15",
    issueDate: "2025-08-15",
    expiryDate: "2026-08-15", // Expired
    daysUntilExpiry: -18,
    alertStatus: "EXPIRED",
    costToRenew: 350000,
    notes: "Uji berkala KIR wajib diperpanjang sebelum mobil beroperasi",
  },
  {
    id: "DOC-STNK-02",
    vehicleId: "B-6789-JKL",
    documentType: "STNK",
    documentNumber: "1192838/STNK/2023",
    issuedDate: "2023-09-18",
    issueDate: "2023-09-18",
    expiryDate: "2026-09-18", // Expiring in 15 days
    daysUntilExpiry: 15,
    alertStatus: "EXPIRING_SOON",
    costToRenew: 3400000,
    notes: "Pajak tahunan jatuh tempo bulan ini",
  },
];
