import { ReservationRecord } from "../types/rental";

export const mockReservations: ReservationRecord[] = [
  // 1. B2C Individual Reservation (Ready to be converted)
  {
    id: "RSV-2026-B2C-101",
    type: "B2C",
    customerId: "CUST-003",
    customerName: "Raditya Dika Pratama",
    customerPhone: "+62 811-3322-110",
    customerEmail: "raditya.dp@gmail.com",
    customerType: "INDIVIDUAL",
    status: "CONFIRMED",
    b2cRequirement: {
      vehicleId: "B-6601-MNO",
      vehicleModel: "Toyota Avanza 1.5 G",
      plateNumber: "B 6601 MNO",
      startDate: "2026-09-02",
      endDate: "2026-09-05",
      durationDays: 3,
      pickupLocation: "Pool Gambir, Jakarta",
      dropoffLocation: "Stasiun Gambir",
      withDriver: true,
      driverOption: "JAJA_DRIVER",
      estimatedTotal: 1950000,
      specialRequests: "Driver wajib berpakaian rapi dan tepat waktu jam 09:30.",
    },
    notes: "Booking via WhatsApp Sales.",
    createdAt: "2026-08-31",
    updatedAt: "2026-09-01",
  },

  // 2. B2B Corporate Sourcing Reservation (With Multi-vendor Quotations & Margin Calculation)
  {
    id: "RSV-2026-B2B-001",
    type: "B2B",
    customerId: "CORP-001",
    customerName: "PT ABC Indonesia",
    customerPhone: "+62 811-9823-110",
    customerEmail: "andi.wijaya@abc-indonesia.co.id",
    customerType: "CORPORATE",
    status: "PROCESSING",
    b2bRequirement: {
      vehicleType: "Toyota Innova Zenix 2.0 V / Reborn",
      quantity: 5,
      durationMonths: 12,
      startDate: "2026-10-01",
      cityLocation: "Jakarta & Cikarang Operations",
      targetBudgetPerUnitMonthly: 14500000,
      driverRequired: true,
      replacementRequired: true,
      maintenanceIncluded: true,
      insuranceIncluded: true,
      notes: "Kebutuhan peremajaan kendaraan operasional level Department Head & VIP.",
    },
    vendorQuotations: [
      {
        id: "VQ-2026-001",
        reservationId: "RSV-2026-B2B-001",
        vendorId: "VND-001",
        vendorName: "PT Mitra Armada Nusantara",
        vehicleModel: "Toyota Innova Zenix 2.0 V CVT 2025",
        quantity: 3,
        vendorCostPerMonth: 11500000,
        customerPricePerMonth: 14500000,
        grossMarginPerUnit: 3000000, // Margin Rp 3.000.000 / unit / bulan
        rentalPeriodMonths: 12,
        maintenanceIncluded: true,
        insuranceIncluded: true,
        driverIncluded: false,
        replacementUnitGuaranteed: true,
        slaDescription: "Garansi unit pengganti maksimal 4 jam untuk area Jabodetabek.",
        status: "ACCEPTED",
        submittedDate: "2026-09-01",
      },
      {
        id: "VQ-2026-002",
        reservationId: "RSV-2026-B2B-001",
        vendorId: "VND-002",
        vendorName: "PT Trans Indo Sejahtera",
        vehicleModel: "Toyota Innova Zenix 2.0 G CVT 2024",
        quantity: 2,
        vendorCostPerMonth: 11000000,
        customerPricePerMonth: 14500000,
        grossMarginPerUnit: 3500000,
        rentalPeriodMonths: 12,
        maintenanceIncluded: true,
        insuranceIncluded: true,
        driverIncluded: false,
        replacementUnitGuaranteed: true,
        slaDescription: "SLA perbaikan darurat 2 jam, unit pengganti maksimal 6 jam.",
        status: "ACCEPTED",
        submittedDate: "2026-09-01",
      },
      {
        id: "VQ-2026-003",
        reservationId: "RSV-2026-B2B-001",
        vendorId: "VND-003",
        vendorName: "CV Rental Sentosa",
        vehicleModel: "Toyota Innova Reborn 2.4 G Diesel 2023",
        quantity: 5,
        vendorCostPerMonth: 12500000,
        customerPricePerMonth: 14500000,
        grossMarginPerUnit: 2000000,
        rentalPeriodMonths: 12,
        maintenanceIncluded: false,
        insuranceIncluded: true,
        driverIncluded: false,
        replacementUnitGuaranteed: false,
        slaDescription: "Perbaikan standar 24 jam.",
        status: "REJECTED",
        submittedDate: "2026-08-30",
        notes: "Ditolak karena tidak ada garansi unit pengganti dan margin terlalu tipis.",
      },
    ],
    negotiationTerms: {
      proposedCustomerPrice: 14500000,
      agreedVendorCost: 11300000,
      expectedMargin: 3200000,
      durationMonths: 12,
      slaTerms: "SLA darurat < 4 jam, penggantian unit gratis.",
      replacementPolicy: "Guaranteed replacement unit within 4-6 hours.",
      maintenancePolicy: "All scheduled maintenance borne by vendor/Jaja.",
      insurancePolicy: "Comprehensive All-Risk + Third Party Liability.",
      notes: "Sepakat 5 unit (3 unit dari PT Mitra Armada, 2 unit dari PT Trans Indo).",
    },
    createdAt: "2026-08-28",
    updatedAt: "2026-09-01",
  },

  // 3. B2C In-Progress Reservation
  {
    id: "RSV-2026-B2C-102",
    type: "B2C",
    customerId: "CUST-004",
    customerName: "Maya Safitri",
    customerPhone: "+62 813-9911-2288",
    customerEmail: "maya.safitri@yahoo.co.id",
    customerType: "INDIVIDUAL",
    status: "CONFIRMED",
    b2cRequirement: {
      vehicleId: "B-5678-ABC",
      vehicleModel: "Toyota Veloz 1.5 Q CVT",
      plateNumber: "B 5678 ABC",
      startDate: "2026-09-06",
      endDate: "2026-09-09",
      durationDays: 3,
      pickupLocation: "Bandara Soekarno-Hatta Terminal 3",
      dropoffLocation: "Hotel Grand Hyatt Jakarta",
      withDriver: false,
      driverOption: "SELF_DRIVE",
      estimatedTotal: 1650000,
    },
    createdAt: "2026-09-01",
    updatedAt: "2026-09-01",
  },

  // 4. B2B Sourcing for Mining / Heavy Client
  {
    id: "RSV-2026-B2B-002",
    type: "B2B",
    customerId: "CORP-002",
    customerName: "PT Maju Bersama",
    customerPhone: "+62 812-3344-5566",
    customerEmail: "bambang.s@majubersama.com",
    customerType: "CORPORATE",
    status: "PROCESSING",
    b2bRequirement: {
      vehicleType: "Mitsubishi Triton 4x4 Double Cabin / Hilux",
      quantity: 4,
      durationMonths: 24,
      startDate: "2026-11-01",
      cityLocation: "Kawasan Industri MM2100 Cikarang",
      targetBudgetPerUnitMonthly: 17500000,
      driverRequired: false,
      replacementRequired: true,
      maintenanceIncluded: true,
      insuranceIncluded: true,
    },
    vendorQuotations: [
      {
        id: "VQ-2026-004",
        reservationId: "RSV-2026-B2B-002",
        vendorId: "VND-001",
        vendorName: "PT Mitra Armada Nusantara",
        vehicleModel: "Mitsubishi Triton 2.4 Ultimate 4x4 MT 2025",
        quantity: 4,
        vendorCostPerMonth: 14000000,
        customerPricePerMonth: 17500000,
        grossMarginPerUnit: 3500000,
        rentalPeriodMonths: 24,
        maintenanceIncluded: true,
        insuranceIncluded: true,
        driverIncluded: false,
        replacementUnitGuaranteed: true,
        slaDescription: "SLA penggantian unit < 6 jam di area industri.",
        status: "PENDING",
        submittedDate: "2026-09-02",
      },
    ],
    createdAt: "2026-09-02",
    updatedAt: "2026-09-02",
  },
];
