import { ScheduleEvent } from "../types/schedule";

export const mockScheduleEvents: ScheduleEvent[] = [
  // 1. September 1, 2026
  {
    id: "SCH-2026-001",
    title: "Pengambilan Mobil B2C (Handover)",
    type: "VEHICLE_PICKUP",
    date: "2026-09-01",
    time: "08:30",
    vehicleId: "B-1234-XYZ",
    plateNumber: "B 1234 XYZ",
    vehicleModel: "Toyota Innova Zenix 2.0 V CVT",
    customerName: "Hendrawan Putra",
    customerId: "CUST-001",
    status: "COMPLETED",
    priority: "HIGH",
    description: "Serah terima kunci dan pengisian BAST pre-rental di Pool SCBD.",
    location: "Pool SCBD Jakarta Selatan",
    actionUrl: "/operations/rentals/RNT-B2C-2026-001",
    actionLabel: "Lihat Rental",
  },
  {
    id: "SCH-2026-002",
    title: "Inspeksi Pre-Rental",
    type: "INSPECTION_SCHEDULED",
    date: "2026-09-01",
    time: "07:45",
    vehicleId: "B-1234-XYZ",
    plateNumber: "B 1234 XYZ",
    vehicleModel: "Toyota Innova Zenix 2.0 V CVT",
    customerName: "Hendrawan Putra",
    status: "COMPLETED",
    priority: "HIGH",
    description: "Inspeksi kondisi fisik dan checklist 5 area sebelum jalan.",
    location: "Pool SCBD Jakarta Selatan",
    actionUrl: "/operations/inspections/INSP-2026-001",
    actionLabel: "Lihat Inspeksi",
  },
  {
    id: "SCH-2026-003",
    title: "Jatuh Tempo Pajak Tahunan STNK",
    type: "DOCUMENT_EXPIRY",
    date: "2026-09-01",
    time: "10:00",
    vehicleId: "B-3321-OPQ",
    plateNumber: "B 3321 OPQ",
    vehicleModel: "Honda HR-V 1.5 SE CVT",
    vendorName: "PT Jaja Rent Indonesia",
    status: "COMPLETED",
    priority: "CRITICAL",
    description: "Perpanjangan PKB & SWDKLLJ tahunan di Samsat Jakarta Barat.",
    location: "Samsat Jakarta Barat",
    actionUrl: "/operations/documents",
    actionLabel: "Lihat Dokumen",
  },

  // 2. September 3, 2026 (Today)
  {
    id: "SCH-2026-004",
    title: "Servis Berkala 85.000 KM",
    type: "MAINTENANCE_DUE",
    date: "2026-09-03",
    time: "09:00",
    vehicleId: "B-7711-GHY",
    plateNumber: "B 7711 GHY",
    vehicleModel: "Mitsubishi Pajero Sport Dakar 4x2",
    status: "TODAY",
    priority: "CRITICAL",
    description: "Ganti oli mesin sintetis, filter oli, balancing, spooring.",
    location: "AutoCare Pulogadung",
    actionUrl: "/operations/maintenance",
    actionLabel: "Lihat Servis",
  },
  {
    id: "SCH-2026-005",
    title: "Pengembalian Unit B2C (Return)",
    type: "VEHICLE_RETURN",
    date: "2026-09-03",
    time: "14:00",
    vehicleId: "B-5678-ABC",
    plateNumber: "B 5678 ABC",
    vehicleModel: "Toyota Veloz 1.5 Q CVT TSS",
    customerName: "Bambang Wijaya",
    customerId: "CUST-002",
    status: "TODAY",
    priority: "HIGH",
    description: "Pengembalian unit sewa harian dan pemeriksaan BBM & kebersihan.",
    location: "Pool Kebon Jeruk Jakarta Barat",
    actionUrl: "/operations/rentals/RNT-B2C-2026-002",
    actionLabel: "Lihat Rental",
  },
  {
    id: "SCH-2026-006",
    title: "Inspeksi Pasca-Sewa (Return)",
    type: "INSPECTION_SCHEDULED",
    date: "2026-09-03",
    time: "14:30",
    vehicleId: "B-5678-ABC",
    plateNumber: "B 5678 ABC",
    vehicleModel: "Toyota Veloz 1.5 Q CVT TSS",
    status: "TODAY",
    priority: "NORMAL",
    description: "Pemeriksaan goresan bodi, interior dan kelengkapan tools mobil.",
    location: "Pool Kebon Jeruk",
    actionUrl: "/operations/inspections/new",
    actionLabel: "Buat Inspeksi",
  },
  {
    id: "SCH-2026-007",
    title: "Jatuh Tempo Uji Berkala (KIR)",
    type: "DOCUMENT_EXPIRY",
    date: "2026-09-03",
    time: "11:00",
    vehicleId: "B-9012-DEF",
    plateNumber: "B 9012 DEF",
    vehicleModel: "Daihatsu Gran Max Blind Van",
    vendorName: "PT Logistik Prima Express",
    status: "TODAY",
    priority: "HIGH",
    description: "Uji KIR berkala 6 bulanan untuk unit blind van operasional.",
    location: "Dishub Ujung Menteng",
    actionUrl: "/operations/documents",
    actionLabel: "Lihat Dokumen",
  },

  // 3. September 5, 2026
  {
    id: "SCH-2026-008",
    title: "Kontrak Fleet Habis (Expiring)",
    type: "CONTRACT_EXPIRY",
    date: "2026-09-05",
    time: "17:00",
    vehicleId: "B-4433-JKL",
    plateNumber: "B 4433 JKL",
    vehicleModel: "Toyota Avanza 1.5 G CVT",
    customerName: "PT ABC Indonesia",
    customerId: "CORP-001",
    status: "UPCOMING",
    priority: "CRITICAL",
    description: "Masa kontrak operasional 1 tahun berakhir. Negosiasi perpanjangan addendum.",
    location: "Kantor Pusat SCBD",
    actionUrl: "/operations/contracts/CTR-2026-001",
    actionLabel: "Lihat Kontrak",
  },
  {
    id: "SCH-2026-009",
    title: "Pengambilan Armada Baru Vendor",
    type: "VEHICLE_PICKUP",
    date: "2026-09-05",
    time: "10:00",
    vehicleId: "B-8822-MNO",
    plateNumber: "B 8822 MNO",
    vehicleModel: "Hyundai Ioniq 5 Signature Long Range",
    vendorName: "PT Nusantara Auto Rent",
    status: "UPCOMING",
    priority: "HIGH",
    description: "Onboarding unit EV baru masuk ke pool fleet Jaja.",
    location: "Pool TB Simatupang",
    actionUrl: "/fleet/B-8822-MNO",
    actionLabel: "Lihat Unit",
  },

  // 4. September 8, 2026
  {
    id: "SCH-2026-010",
    title: "Penggantian 4 Ban Aus",
    type: "MAINTENANCE_DUE",
    date: "2026-09-08",
    time: "13:00",
    vehicleId: "B-2299-STU",
    plateNumber: "B 2299 STU",
    vehicleModel: "Toyota Fortuner 2.8 GR Sport 4x4",
    status: "UPCOMING",
    priority: "HIGH",
    description: "Penggantian 4 ban Bridgestone Dueler AT dan spooring 3D.",
    location: "Bengkel Ban Bintaro",
    actionUrl: "/operations/maintenance",
    actionLabel: "Lihat Servis",
  },
  {
    id: "SCH-2026-011",
    title: "Inspeksi Rutin Armada Vendor",
    type: "INSPECTION_SCHEDULED",
    date: "2026-09-08",
    time: "15:00",
    vehicleId: "B-6677-VWX",
    plateNumber: "B 6677 VWX",
    vehicleModel: "Mitsubishi Xpander Ultimate CVT",
    vendorName: "CV Mitra Mandiri Rent",
    status: "UPCOMING",
    priority: "NORMAL",
    description: "Pemeriksaan rutin triwulan kondisi unit sewa dari vendor.",
    location: "Pool Cilandak",
    actionUrl: "/operations/inspections",
    actionLabel: "Lihat Inspeksi",
  },

  // 5. September 10, 2026
  {
    id: "SCH-2026-012",
    title: "Jatuh Tempo Polis Asuransi All-Risk",
    type: "DOCUMENT_EXPIRY",
    date: "2026-09-10",
    time: "12:00",
    vehicleId: "B-7788-YZA",
    plateNumber: "B 7788 YZA",
    vehicleModel: "Toyota Alphard 2.5 G Executive",
    status: "UPCOMING",
    priority: "CRITICAL",
    description: "Perpanjangan premi asuransi komersial TJH III Garda Oto.",
    location: "Finance & Legal Office",
    actionUrl: "/operations/documents",
    actionLabel: "Lihat Dokumen",
  },
  {
    id: "SCH-2026-013",
    title: "Serah Terima Kontrak Korporat 5 Unit",
    type: "VEHICLE_PICKUP",
    date: "2026-09-10",
    time: "08:00",
    customerName: "PT Surya Logistik Nusantara",
    customerId: "CORP-003",
    status: "UPCOMING",
    priority: "HIGH",
    description: "Delivery 5 unit Innova Zenix ke kantor operasional klien di Cikarang.",
    location: "Kawasan Industri GIIC Cikarang",
    actionUrl: "/operations/contracts",
    actionLabel: "Lihat Kontrak",
  },

  // 6. September 15, 2026 (Multiple events test)
  {
    id: "SCH-2026-014",
    title: "Kontrak Habis PT Global Distribusi",
    type: "CONTRACT_EXPIRY",
    date: "2026-09-15",
    time: "17:00",
    customerName: "PT Global Distribusi",
    customerId: "CORP-002",
    status: "UPCOMING",
    priority: "HIGH",
    description: "Akhir periode sewa 3 unit blind van logistik.",
    actionUrl: "/operations/contracts",
    actionLabel: "Lihat Kontrak",
  },
  {
    id: "SCH-2026-015",
    title: "Servis Berkala 40.000 KM",
    type: "MAINTENANCE_DUE",
    date: "2026-09-15",
    time: "09:30",
    plateNumber: "B 1010 ABC",
    vehicleModel: "Honda Brio RS CVT",
    status: "UPCOMING",
    priority: "NORMAL",
    location: "Bengkel Honda Pondok Indah",
    actionUrl: "/operations/maintenance",
    actionLabel: "Lihat Servis",
  },
  {
    id: "SCH-2026-016",
    title: "Inspeksi Audit Bulanan Pool",
    type: "INSPECTION_SCHEDULED",
    date: "2026-09-15",
    time: "11:00",
    plateNumber: "B 2020 BCD",
    vehicleModel: "Toyota Raize 1.0 Turbo GR",
    status: "UPCOMING",
    priority: "NORMAL",
    location: "Pool Kebon Jeruk",
    actionUrl: "/operations/inspections",
    actionLabel: "Lihat Inspeksi",
  },
  {
    id: "SCH-2026-017",
    title: "Pengembalian Rental Harian",
    type: "VEHICLE_RETURN",
    date: "2026-09-15",
    time: "16:00",
    plateNumber: "B 3030 CDE",
    vehicleModel: "Toyota Veloz 1.5 Q",
    customerName: "Siti Rahma",
    status: "UPCOMING",
    priority: "NORMAL",
    location: "Pool SCBD",
    actionUrl: "/operations/rentals",
    actionLabel: "Lihat Rental",
  },
  {
    id: "SCH-2026-018",
    title: "Pembaruan Sertifikat Uji Emisi",
    type: "DOCUMENT_EXPIRY",
    date: "2026-09-15",
    time: "14:00",
    plateNumber: "B 4040 DEF",
    vehicleModel: "Suzuki Ertiga Hybrid GX",
    status: "UPCOMING",
    priority: "NORMAL",
    location: "Bengkel Uji Emisi Jaksel",
    actionUrl: "/operations/documents",
    actionLabel: "Lihat Dokumen",
  },

  // 7. September 22, 2026
  {
    id: "SCH-2026-019",
    title: "Servis Rem & Ganti Kampas",
    type: "MAINTENANCE_DUE",
    date: "2026-09-22",
    time: "10:00",
    plateNumber: "B 5050 EFG",
    vehicleModel: "Toyota HiAce Premio 2.8 MT",
    status: "UPCOMING",
    priority: "HIGH",
    location: "AutoCare Sunter",
    actionUrl: "/operations/maintenance",
    actionLabel: "Lihat Servis",
  },

  // 8. September 30, 2026
  {
    id: "SCH-2026-020",
    title: "Tutup Buku Kontrak Q3",
    type: "OTHER_EVENT",
    date: "2026-09-30",
    time: "18:00",
    status: "UPCOMING",
    priority: "HIGH",
    description: "Rekonsiliasi billing kontrak korporat dan settlement vendor Q3.",
    location: "Kantor Pusat Jaja Rent",
    actionUrl: "/reports",
    actionLabel: "Lihat Laporan",
  },
];

