import { Vehicle } from "../types/fleet";

export const mockVehicles: Vehicle[] = [
  {
    id: "B-1234-XYZ",
    plateNumber: "B 1234 XYZ",
    brand: "Toyota",
    model: "Innova Zenix 2.0 V CVT",
    year: 2024,
    color: "Platinum White Pearl",
    transmission: "Automatic",
    fuelType: "Hybrid",
    seatCapacity: 7,
    vin: "MHFXW43G6R0129841",
    engineNumber: "M20A-FKS-993821",
    odometer: 82421,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2B-2026-001",
    currentCustomerId: "CORP-001",
    currentCustomerName: "PT ABC Indonesia",
    currentRentalType: "B2B",
    currentDriverName: "Budi Santoso",
    currentContractId: "CTR-2026-001",
    locationCity: "Jakarta Selatan",
    locationArea: "SCBD Lot 8, Sudirman",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "2 minutes ago",
    latitude: -6.2255,
    longitude: 106.8095,
    speed: 38,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 85000,
    dailyRateB2C: 850000,
    monthlyRateB2B: 14500000,
  },
  {
    id: "B-5678-ABC",
    plateNumber: "B 5678 ABC",
    brand: "Toyota",
    model: "Veloz 1.5 Q CVT TSS",
    year: 2023,
    color: "Black Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHFZ781A8P0031892",
    engineNumber: "2NR-VE-448102",
    odometer: 45210,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "AVAILABLE",
    lifecycleStage: "AVAILABLE",
    locationCity: "Jakarta Barat",
    locationArea: "Pool Kebon Jeruk",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "Just now",
    latitude: -6.1754,
    longitude: 106.7725,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 50000,
    dailyRateB2C: 550000,
    monthlyRateB2B: 9500000,
  },
  {
    id: "B-2345-DEF",
    plateNumber: "B 2345 DEF",
    brand: "Toyota",
    model: "Fortuner 2.8 GR Sport 4x4",
    year: 2024,
    color: "Attitude Black",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatCapacity: 7,
    vin: "MHFY994F7R0882190",
    engineNumber: "1GD-FTV-882713",
    odometer: 31050,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2C-2026-088",
    currentCustomerId: "CUST-009",
    currentCustomerName: "Hendrawan Putra",
    currentRentalType: "B2C",
    currentDriverName: "Asep Sunandar (Jaja Driver)",
    locationCity: "Jakarta Pusat",
    locationArea: "Grand Indonesia Mall",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "4 minutes ago",
    latitude: -6.1952,
    longitude: 106.8217,
    speed: 24,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 35000,
    dailyRateB2C: 1400000,
    monthlyRateB2B: 24000000,
  },
  {
    id: "B-8899-KLU",
    plateNumber: "B 8899 KLU",
    brand: "Mitsubishi",
    model: "Xpander Ultimate CVT",
    year: 2023,
    color: "Blade Silver Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MK2NC1W18P0099412",
    engineNumber: "4A91-094812",
    odometer: 58920,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "MAINTENANCE",
    lifecycleStage: "MAINTENANCE",
    currentContractId: "CTR-2026-001",
    currentCustomerId: "CORP-001",
    currentCustomerName: "PT ABC Indonesia",
    locationCity: "Jakarta Timur",
    locationArea: "Bengkel AutoCare Pulogadung",
    gpsStatus: "IDLE",
    lastGpsUpdate: "1 hour ago",
    latitude: -6.1932,
    longitude: 106.9012,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "IN_PROGRESS",
    nextServiceOdometer: 60000,
    dailyRateB2C: 600000,
    monthlyRateB2B: 10000000,
  },
  {
    id: "B-9123-POX",
    plateNumber: "B 9123 POX",
    brand: "Toyota",
    model: "HiAce Commuter 2.5 Manual",
    year: 2022,
    color: "Silver Metallic",
    transmission: "Manual",
    fuelType: "Diesel",
    seatCapacity: 15,
    vin: "MHFLH11R8N0081290",
    engineNumber: "2KD-FTV-771822",
    odometer: 114500,
    ownership: "VENDOR_OWNED",
    vendorName: "PT Mitra Armada Nusantara",
    businessEligibility: "B2B",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2B-2026-012",
    currentCustomerId: "CORP-003",
    currentCustomerName: "PT Nusantara Logistik",
    currentRentalType: "B2B",
    currentContractId: "CTR-2026-003",
    locationCity: "Tangerang",
    locationArea: "Bandara Soekarno Hatta Cargo",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "5 minutes ago",
    latitude: -6.1275,
    longitude: 106.6537,
    speed: 45,
    documentStatus: "EXPIRING_SOON",
    maintenanceStatus: "OK",
    nextServiceOdometer: 120000,
    monthlyRateB2B: 18000000,
  },
  {
    id: "B-3344-ZZA",
    plateNumber: "B 3344 ZZA",
    brand: "Hyundai",
    model: "Stargazer Prime IVT",
    year: 2023,
    color: "Midnight Black Pearl",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "KMHCT81E4P0018442",
    engineNumber: "G4FL-661902",
    odometer: 28400,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "AVAILABLE",
    lifecycleStage: "AVAILABLE",
    locationCity: "Jakarta Selatan",
    locationArea: "Pool Cilandak",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "10 minutes ago",
    latitude: -6.2941,
    longitude: 106.7993,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 30000,
    dailyRateB2C: 580000,
    monthlyRateB2B: 9800000,
  },
  {
    id: "B-7711-GHY",
    plateNumber: "B 7711 GHY",
    brand: "Honda",
    model: "HR-V 1.5 SE CVT",
    year: 2023,
    color: "Ignite Red Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 5,
    vin: "MHRRV3885P0027719",
    engineNumber: "L15ZF-382910",
    odometer: 39800,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2C-2026-091",
    currentCustomerId: "CUST-015",
    currentCustomerName: "Jessica Tanuwidjaja",
    currentRentalType: "B2C",
    locationCity: "Tangerang Selatan",
    locationArea: "BSD City Green Office Park",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "1 minute ago",
    latitude: -6.3015,
    longitude: 106.6521,
    speed: 52,
    documentStatus: "OK",
    maintenanceStatus: "DUE",
    nextServiceOdometer: 40000,
    dailyRateB2C: 750000,
    monthlyRateB2B: 12500000,
  },
  {
    id: "B-4422-RST",
    plateNumber: "B 4422 RST",
    brand: "Toyota",
    model: "Innova Reborn 2.4 G Diesel AT",
    year: 2022,
    color: "Super White",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatCapacity: 7,
    vin: "MHFXW42G9N0049281",
    engineNumber: "2GD-FTV-551029",
    odometer: 98400,
    ownership: "VENDOR_OWNED",
    vendorName: "PT Trans Indo Sejahtera",
    businessEligibility: "B2B",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2B-2026-022",
    currentCustomerId: "CORP-002",
    currentCustomerName: "PT Maju Bersama",
    currentRentalType: "B2B",
    currentDriverName: "Supriyanto",
    currentContractId: "CTR-2026-002",
    locationCity: "Bekasi",
    locationArea: "Kawasan Industri MM2100 Cikarang",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "7 minutes ago",
    latitude: -6.3129,
    longitude: 107.0984,
    speed: 62,
    documentStatus: "EXPIRED",
    maintenanceStatus: "OK",
    nextServiceOdometer: 100000,
    monthlyRateB2B: 13000000,
  },
  {
    id: "B-6601-MNO",
    plateNumber: "B 6601 MNO",
    brand: "Toyota",
    model: "Avanza 1.5 G CVT",
    year: 2023,
    color: "Silver Mica Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHFZ781E7P0019283",
    engineNumber: "2NR-VE-110948",
    odometer: 51200,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "RESERVED",
    lifecycleStage: "RESERVED",
    locationCity: "Jakarta Pusat",
    locationArea: "Pool Gambir",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "15 minutes ago",
    latitude: -6.1764,
    longitude: 106.8306,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 55000,
    dailyRateB2C: 450000,
    monthlyRateB2B: 8000000,
  },
  {
    id: "B-1099-QWE",
    plateNumber: "B 1099 QWE",
    brand: "Hyundai",
    model: "Ioniq 5 Signature Long Range",
    year: 2024,
    color: "Gravity Gold Matte",
    transmission: "Automatic",
    fuelType: "Electric",
    seatCapacity: 5,
    vin: "KMHNE81V8R0010928",
    engineNumber: "EM15-E882901",
    odometer: 18450,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "INSPECTION",
    lifecycleStage: "INSPECTION",
    locationCity: "Jakarta Selatan",
    locationArea: "Pool Cilandak Inspection Bay",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "8 minutes ago",
    latitude: -6.2945,
    longitude: 106.7989,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 25000,
    dailyRateB2C: 1850000,
    monthlyRateB2B: 32000000,
  },
  {
    id: "D-1234-EF",
    plateNumber: "D 1234 EF",
    brand: "Toyota",
    model: "Innova Zenix 2.0 Q Hybrid TSS",
    year: 2024,
    color: "Attitude Black",
    transmission: "Automatic",
    fuelType: "Hybrid",
    seatCapacity: 7,
    vin: "MHFXW43H2R0119284",
    engineNumber: "M20A-FXS-381902",
    odometer: 32100,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2B-2026-009",
    currentCustomerId: "CORP-004",
    currentCustomerName: "PT Sinar Abadi",
    currentRentalType: "B2B",
    currentDriverName: "Cecep Supriatna",
    currentContractId: "CTR-2026-004",
    locationCity: "Bandung",
    locationArea: "Dago Resik Office Park",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "3 minutes ago",
    latitude: -6.8854,
    longitude: 107.6138,
    speed: 40,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 35000,
    dailyRateB2C: 950000,
    monthlyRateB2B: 16000000,
  },
  {
    id: "B-5566-VBN",
    plateNumber: "B 5566 VBN",
    brand: "Mitsubishi",
    model: "Pajero Sport 2.4 Dakar Ultimate 4x2",
    year: 2023,
    color: "Deep Bronze Metallic",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatCapacity: 7,
    vin: "MK2KS1W18P0038812",
    engineNumber: "4N15-882910",
    odometer: 64120,
    ownership: "VENDOR_OWNED",
    vendorName: "PT Sentra Armada Prima",
    businessEligibility: "B2B",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2B-2026-005",
    currentCustomerId: "CORP-005",
    currentCustomerName: "PT Mandiri Distribusi",
    currentRentalType: "B2B",
    currentContractId: "CTR-2026-005",
    locationCity: "Jakarta Utara",
    locationArea: "Pelabuhan Tanjung Priok Gate 3",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "6 minutes ago",
    latitude: -6.1089,
    longitude: 106.8812,
    speed: 15,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 70000,
    monthlyRateB2B: 22000000,
  },
  {
    id: "B-8182-JKL",
    plateNumber: "B 8182 JKL",
    brand: "Toyota",
    model: "Veloz 1.5 Q CVT",
    year: 2023,
    color: "Silver Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHFZ781E3P0022391",
    engineNumber: "2NR-VE-662910",
    odometer: 48900,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "AVAILABLE",
    lifecycleStage: "AVAILABLE",
    locationCity: "Jakarta Selatan",
    locationArea: "Pool Cilandak",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "Just now",
    latitude: -6.2943,
    longitude: 106.7995,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 50000,
    dailyRateB2C: 550000,
    monthlyRateB2B: 9500000,
  },
  {
    id: "B-9988-TYU",
    plateNumber: "B 9988 TYU",
    brand: "Daihatsu",
    model: "GranMax Blind Van 1.3",
    year: 2022,
    color: "Icy White",
    transmission: "Manual",
    fuelType: "Bensin",
    seatCapacity: 2,
    vin: "MHKF811A6N0019283",
    engineNumber: "K3-DE-882910",
    odometer: 132000,
    ownership: "VENDOR_OWNED",
    vendorName: "PT Logistik Armada Mandiri",
    businessEligibility: "B2B",
    status: "MAINTENANCE",
    lifecycleStage: "MAINTENANCE",
    locationCity: "Tangerang",
    locationArea: "Bengkel Sentosa Daan Mogot",
    gpsStatus: "OFFLINE",
    lastGpsUpdate: "4 hours ago",
    latitude: -6.1554,
    longitude: 106.6781,
    speed: 0,
    documentStatus: "EXPIRING_SOON",
    maintenanceStatus: "IN_PROGRESS",
    nextServiceOdometer: 135000,
    monthlyRateB2B: 6500000,
  },
  {
    id: "B-4433-CVB",
    plateNumber: "B 4433 CVB",
    brand: "Honda",
    model: "BR-V 1.5 Prestige with Sensing",
    year: 2023,
    color: "Meteoroid Gray Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHRDG3887P0011928",
    engineNumber: "L15ZF-992819",
    odometer: 41200,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2C-2026-095",
    currentCustomerId: "CUST-021",
    currentCustomerName: "Dian Anggraini",
    currentRentalType: "B2C",
    locationCity: "Jakarta Selatan",
    locationArea: "Pondok Indah Mall 2",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "3 minutes ago",
    latitude: -6.2654,
    longitude: 106.7842,
    speed: 18,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 45000,
    dailyRateB2C: 620000,
    monthlyRateB2B: 10500000,
  },
  {
    id: "B-2211-KKK",
    plateNumber: "B 2211 KKK",
    brand: "Toyota",
    model: "Innova Zenix 2.0 G CVT",
    year: 2024,
    color: "Silver Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHFXW43F5R0099812",
    engineNumber: "M20A-FKS-112938",
    odometer: 24500,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "AVAILABLE",
    lifecycleStage: "AVAILABLE",
    locationCity: "Jakarta Timur",
    locationArea: "Pool Halim Perdanakusuma",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "12 minutes ago",
    latitude: -6.2575,
    longitude: 106.8842,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 30000,
    dailyRateB2C: 750000,
    monthlyRateB2B: 13000000,
  },
  {
    id: "B-7890-WSX",
    plateNumber: "B 7890 WSX",
    brand: "Toyota",
    model: "Avanza 1.5 G CVT",
    year: 2023,
    color: "Black Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHFZ781E2P0044512",
    engineNumber: "2NR-VE-991823",
    odometer: 62100,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "DOCUMENT_HOLD",
    lifecycleStage: "DOCUMENT_CHECK",
    locationCity: "Jakarta Barat",
    locationArea: "Pool Kebon Jeruk",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "30 minutes ago",
    latitude: -6.1751,
    longitude: 106.7728,
    speed: 0,
    documentStatus: "EXPIRED",
    maintenanceStatus: "OK",
    nextServiceOdometer: 65000,
    dailyRateB2C: 450000,
    monthlyRateB2B: 8000000,
  },
  {
    id: "B-3199-OPP",
    plateNumber: "B 3199 OPP",
    brand: "Hyundai",
    model: "Stargazer Active MT",
    year: 2023,
    color: "Magnetic Silver Metallic",
    transmission: "Manual",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "KMHCT81E1P0029103",
    engineNumber: "G4FL-881923",
    odometer: 54100,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2B-2026-031",
    currentCustomerId: "CORP-006",
    currentCustomerName: "PT Astra Surya",
    currentRentalType: "B2B",
    currentContractId: "CTR-2026-006",
    locationCity: "Jakarta Utara",
    locationArea: "Kelapa Gading Boulevard",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "5 minutes ago",
    latitude: -6.1582,
    longitude: 106.9084,
    speed: 32,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 60000,
    dailyRateB2C: 500000,
    monthlyRateB2B: 8800000,
  },
  {
    id: "B-6721-EDC",
    plateNumber: "B 6721 EDC",
    brand: "Toyota",
    model: "Fortuner 2.4 VRZ 4x2",
    year: 2022,
    color: "Phantom Brown Metallic",
    transmission: "Automatic",
    fuelType: "Diesel",
    seatCapacity: 7,
    vin: "MHFY994F2N0077812",
    engineNumber: "2GD-FTV-992814",
    odometer: 89300,
    ownership: "VENDOR_OWNED",
    vendorName: "PT Sentra Armada Prima",
    businessEligibility: "B2B",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2B-2026-041",
    currentCustomerId: "CORP-007",
    currentCustomerName: "PT Graha Finansial",
    currentRentalType: "B2B",
    currentContractId: "CTR-2026-007",
    locationCity: "Jakarta Selatan",
    locationArea: "Mega Kuningan Barat",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "1 minute ago",
    latitude: -6.2291,
    longitude: 106.8284,
    speed: 28,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 90000,
    monthlyRateB2B: 20000000,
  },
  {
    id: "B-5012-YTR",
    plateNumber: "B 5012 YTR",
    brand: "Mitsubishi",
    model: "Xpander Cross Premium Package",
    year: 2023,
    color: "Graphite Gray Metallic",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MK2NC1W12P0049281",
    engineNumber: "4A91-551928",
    odometer: 37400,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "AVAILABLE",
    lifecycleStage: "AVAILABLE",
    locationCity: "Bekasi",
    locationArea: "Pool Summarecon Bekasi",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "8 minutes ago",
    latitude: -6.2215,
    longitude: 107.0018,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 40000,
    dailyRateB2C: 650000,
    monthlyRateB2B: 11000000,
  },
  {
    id: "B-1122-AAA",
    plateNumber: "B 1122 AAA",
    brand: "Toyota",
    model: "Innova Zenix 2.0 V Hybrid",
    year: 2024,
    color: "Attitude Black",
    transmission: "Automatic",
    fuelType: "Hybrid",
    seatCapacity: 7,
    vin: "MHFXW43G1R0155281",
    engineNumber: "M20A-FXS-991823",
    odometer: 14200,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "AVAILABLE",
    lifecycleStage: "AVAILABLE",
    locationCity: "Jakarta Selatan",
    locationArea: "Pool Cilandak",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "Just now",
    latitude: -6.2948,
    longitude: 106.7991,
    speed: 0,
    documentStatus: "OK",
    maintenanceStatus: "OK",
    nextServiceOdometer: 20000,
    dailyRateB2C: 850000,
    monthlyRateB2B: 14500000,
  },
  {
    id: "B-9021-POI",
    plateNumber: "B 9021 POI",
    brand: "Toyota",
    model: "Veloz 1.5 Q CVT",
    year: 2023,
    color: "Platinum White Pearl",
    transmission: "Automatic",
    fuelType: "Bensin",
    seatCapacity: 7,
    vin: "MHFZ781E9P0088192",
    engineNumber: "2NR-VE-332918",
    odometer: 49800,
    ownership: "JAJA_OWNED",
    businessEligibility: "BOTH",
    status: "RENTED",
    lifecycleStage: "RENTED",
    currentRentalId: "RNT-B2C-2026-098",
    currentCustomerId: "CUST-034",
    currentCustomerName: "Rizky Ramadhan",
    currentRentalType: "B2C",
    locationCity: "Bandung",
    locationArea: "Jl. R.E Martadinata No. 42",
    gpsStatus: "ONLINE",
    lastGpsUpdate: "4 minutes ago",
    latitude: -6.9082,
    longitude: 107.6189,
    speed: 48,
    documentStatus: "OK",
    maintenanceStatus: "DUE",
    nextServiceOdometer: 50000,
    dailyRateB2C: 550000,
    monthlyRateB2B: 9500000,
  },
];
