import { InspectionItem, TestDriveItem } from "@/lib/types/inspection";

export const defaultExteriorItems: InspectionItem[] = [
  { id: "ext_antenna", name: "Antenna", nameId: "Antena Radio", category: "EXTERIOR" },
  { id: "ext_roof", name: "Roof Panel", nameId: "Atap Kendaraan", category: "EXTERIOR" },
  { id: "ext_front_bumper", name: "Front Bumper", nameId: "Bumper Depan", category: "EXTERIOR" },
  { id: "ext_rear_bumper", name: "Rear Bumper", nameId: "Bumper Belakang", category: "EXTERIOR" },
  { id: "ext_front_grille", name: "Front Grille", nameId: "Grille Depan", category: "EXTERIOR" },
  { id: "ext_hood", name: "Hood / Bonnet", nameId: "Kap Mesin", category: "EXTERIOR" },
  { id: "ext_trunk", name: "Trunk Lid / Tailgate", nameId: "Pintu Bagasi Belakang", category: "EXTERIOR" },
  { id: "ext_front_left_fender", name: "Front Left Fender", nameId: "Fender Depan Kiri", category: "EXTERIOR" },
  { id: "ext_front_right_fender", name: "Front Right Fender", nameId: "Fender Depan Kanan", category: "EXTERIOR" },
  { id: "ext_rear_left_fender", name: "Rear Left Quarter Panel", nameId: "Fender / Quarter Belakang Kiri", category: "EXTERIOR" },
  { id: "ext_rear_right_fender", name: "Rear Right Quarter Panel", nameId: "Fender / Quarter Belakang Kanan", category: "EXTERIOR" },
  { id: "ext_front_left_door", name: "Front Left Door", nameId: "Pintu Depan Kiri", category: "EXTERIOR" },
  { id: "ext_front_right_door", name: "Front Right Door", nameId: "Pintu Depan Kanan", category: "EXTERIOR" },
  { id: "ext_rear_left_door", name: "Rear Left Door", nameId: "Pintu Belakang Kiri", category: "EXTERIOR" },
  { id: "ext_rear_right_door", name: "Rear Right Door", nameId: "Pintu Belakang Kanan", category: "EXTERIOR" },
  { id: "ext_front_windshield", name: "Front Windshield", nameId: "Kaca Depan Utama", category: "EXTERIOR" },
  { id: "ext_rear_windshield", name: "Rear Windshield", nameId: "Kaca Belakang", category: "EXTERIOR" },
  { id: "ext_left_windows", name: "Left Door Glasses", nameId: "Kaca Pintu Samping Kiri", category: "EXTERIOR" },
  { id: "ext_right_windows", name: "Right Door Glasses", nameId: "Kaca Pintu Samping Kanan", category: "EXTERIOR" },
  { id: "ext_left_mirror", name: "Left Side Mirror", nameId: "Kaca Spion Luar Kiri", category: "EXTERIOR" },
  { id: "ext_right_mirror", name: "Right Side Mirror", nameId: "Kaca Spion Luar Kanan", category: "EXTERIOR" },
  { id: "ext_headlights", name: "Headlights & DRL", nameId: "Lampu Utama & Senja (Kiri & Kanan)", category: "EXTERIOR" },
  { id: "ext_taillights", name: "Taillights & Brake Lamps", nameId: "Lampu Belakang & Rem (Kiri & Kanan)", category: "EXTERIOR" },
  { id: "ext_fog_lamps", name: "Fog Lamps", nameId: "Lampu Kabut", category: "EXTERIOR" },
  { id: "ext_front_left_tire", name: "Front Left Tire & Wheel", nameId: "Ban & Velg Depan Kiri", category: "EXTERIOR" },
  { id: "ext_front_right_tire", name: "Front Right Tire & Wheel", nameId: "Ban & Velg Depan Kanan", category: "EXTERIOR" },
  { id: "ext_rear_left_tire", name: "Rear Left Tire & Wheel", nameId: "Ban & Velg Belakang Kiri", category: "EXTERIOR" },
  { id: "ext_rear_right_tire", name: "Rear Right Tire & Wheel", nameId: "Ban & Velg Belakang Kanan", category: "EXTERIOR" },
  { id: "ext_spare_tire", name: "Spare Tire & Wheel", nameId: "Ban Serep & Velg Cadangan", category: "EXTERIOR" },
  { id: "ext_side_skirts", name: "Side Skirts & Body Molding", nameId: "Side Skirt & Aksesoris Eksterior", category: "EXTERIOR" },
];

export const defaultInteriorItems: InspectionItem[] = [
  { id: "int_audio_system", name: "Audio System / Head Unit", nameId: "Audio & Layar Head Unit", category: "INTERIOR" },
  { id: "int_dashboard", name: "Dashboard & Speedometer", nameId: "Dashboard & Instrument Cluster", category: "INTERIOR" },
  { id: "int_glove_box", name: "Glove Box", nameId: "Laci Dashboard (Glove Box)", category: "INTERIOR" },
  { id: "int_steering_wheel", name: "Steering Wheel & Controls", nameId: "Setir Kemudi & Tombol Fungsi", category: "INTERIOR" },
  { id: "int_horn", name: "Horn", nameId: "Klakson", category: "INTERIOR" },
  { id: "int_ac_louvers", name: "AC Louvers & Vents", nameId: "Kisi-Kisi Ventilasi AC", category: "INTERIOR" },
  { id: "int_center_console", name: "Center Console & Armrest", nameId: "Konsol Tengah & Armrest", category: "INTERIOR" },
  { id: "int_driver_seat", name: "Driver Seat Mechanism & Foam", nameId: "Jok Pengemudi & Rel Geser", category: "INTERIOR" },
  { id: "int_passenger_seat", name: "Front Passenger Seat", nameId: "Jok Penumpang Depan", category: "INTERIOR" },
  { id: "int_rear_seats", name: "Rear Passenger Seats (2nd/3rd Row)", nameId: "Jok Penumpang Baris Belakang", category: "INTERIOR" },
  { id: "int_head_rest", name: "Head Rests", nameId: "Sandaran Kepala (Head Rest)", category: "INTERIOR" },
  { id: "int_seatbelt", name: "Seatbelts (All Rows)", nameId: "Sabuk Pengaman Semua Baris", category: "INTERIOR" },
  { id: "int_carpet", name: "Floor Carpet & Mats", nameId: "Karpet Dasar & Karpet Kaki", category: "INTERIOR" },
  { id: "int_ceiling", name: "Ceiling / Headliner", nameId: "Plafon / Langit-Langit Kabin", category: "INTERIOR" },
  { id: "int_inner_mirror", name: "Inner Rearview Mirror", nameId: "Kaca Spion Dalam", category: "INTERIOR" },
  { id: "int_sun_visors", name: "Sun Visors", nameId: "Pelindung Sinar Matahari (Sun Visor)", category: "INTERIOR" },
  { id: "int_front_door_trim", name: "Front Door Trims", nameId: "Trim & Doortrim Pintu Depan", category: "INTERIOR" },
  { id: "int_rear_door_trim", name: "Rear Door Trims", nameId: "Trim & Doortrim Pintu Belakang", category: "INTERIOR" },
  { id: "int_trunk_lining", name: "Trunk Lining & Board", nameId: "Karpet / Dinding Bagasi Belakang", category: "INTERIOR" },
];

export const defaultMechanicalItems: InspectionItem[] = [
  { id: "mech_ac_system", name: "Air Conditioning System", nameId: "Sistem Pendingin AC & Blower", category: "MECHANICAL" },
  { id: "mech_battery", name: "Battery / Aki", nameId: "Aki & Terminal Baterai", category: "MECHANICAL" },
  { id: "mech_compressor_belt", name: "Compressor Belt", nameId: "Tali Kipas AC (Compressor Belt)", category: "MECHANICAL" },
  { id: "mech_power_steering_belt", name: "Power Steering Belt / Fan Belt", nameId: "Fan Belt / Tali Kipas Mesin", category: "MECHANICAL" },
  { id: "mech_engine_oil", name: "Engine Oil Level & Condition", nameId: "Oli Mesin (Volume & Kualitas)", category: "MECHANICAL" },
  { id: "mech_oil_cap", name: "Engine Oil Cap & Gasket", nameId: "Tutup Oli Mesin & Seal", category: "MECHANICAL" },
  { id: "mech_engine_vibration", name: "Engine Vibration & Mounting", nameId: "Getaran Mesin & Engine Mounting", category: "MECHANICAL" },
  { id: "mech_air_filter", name: "Air Filter", nameId: "Filter Udara Mesin", category: "MECHANICAL" },
  { id: "mech_radiator", name: "Radiator & Coolant Level", nameId: "Radiator & Air Reservoir Coolant", category: "MECHANICAL" },
  { id: "mech_brake_fluid", name: "Brake Fluid & Reservoir", nameId: "Minyak Rem & Tabung Reservoir", category: "MECHANICAL" },
  { id: "mech_power_steering", name: "Power Steering Fluid & Rack", nameId: "Sistem Kemudi Power Steering", category: "MECHANICAL" },
  { id: "mech_power_window", name: "Power Window & Central Lock", nameId: "Motor Power Window & Central Lock", category: "MECHANICAL" },
  { id: "mech_alarm_system", name: "Alarm & Keyless System", nameId: "Sistem Alarm & Remote Kunci", category: "MECHANICAL" },
  { id: "mech_transmission_fluid", name: "Transmission Fluid", nameId: "Oli Transmisi (Matik / Manual)", category: "MECHANICAL" },
  { id: "mech_exhaust", name: "Exhaust System / Muffler", nameId: "Saluran Knalpot & Emisi Gas Buang", category: "MECHANICAL" },
  { id: "mech_service_book", name: "Service Book & Tools Set", nameId: "Buku Servis & Toolkit / Dongkrak", category: "MECHANICAL" },
];

export const defaultFrameItems: InspectionItem[] = [
  { id: "frame_spare_tire_box", name: "Spare Tire Well", nameId: "Ruang Dudukan Ban Serep", category: "FRAME" },
  { id: "frame_front_frame", name: "Front Chassis Frame", nameId: "Rangka Chasis Depan", category: "FRAME" },
  { id: "frame_rear_frame", name: "Rear Chassis Frame", nameId: "Rangka Chasis Belakang", category: "FRAME" },
  { id: "frame_lower_front", name: "Lower Front Frame", nameId: "Sasis Bawah Depan / Crossmember", category: "FRAME" },
  { id: "frame_lower_middle", name: "Lower Middle Frame / Floor Pan", nameId: "Lantai Bawah Tengah (Floor Pan)", category: "FRAME" },
  { id: "frame_lower_side", name: "Lower Side Sill Frame (L/R)", nameId: "Ambang Bawah Samping (Side Sill L/R)", category: "FRAME" },
  { id: "frame_front_pillar", name: "Front Pillar (A-Pillar L/R)", nameId: "Pilar Depan (Pilar A Kiri & Kanan)", category: "FRAME" },
  { id: "frame_middle_pillar", name: "Middle Pillar (B-Pillar L/R)", nameId: "Pilar Tengah (Pilar B Kiri & Kanan)", category: "FRAME" },
  { id: "frame_rear_pillar", name: "Rear Pillar (C/D-Pillar L/R)", nameId: "Pilar Belakang (Pilar C/D L/R)", category: "FRAME" },
  { id: "frame_right_wheel_house", name: "Right Wheel House", nameId: "Ruang Roda (Wheel House) Kanan", category: "FRAME" },
  { id: "frame_left_wheel_house", name: "Left Wheel House", nameId: "Ruang Roda (Wheel House) Kiri", category: "FRAME" },
  { id: "frame_radiator_support", name: "Radiator Support Frame & Apron", nameId: "Dudukan Radiator & Apron Mesin", category: "FRAME" },
];

export const defaultTestDriveItems: TestDriveItem[] = [
  {
    id: "td_at_shift_jump",
    name: "AT jumps when shifting",
    nameId: "Hentakan Transmisi saat Perpindahan Gigi",
    status: "NORMAL",
  },
  {
    id: "td_rwd_disturbance",
    name: "Rear wheel drive / Powertrain disturbance",
    nameId: "Gangguan / Getaran Penggerak Roda & Gardan",
    status: "NORMAL",
  },
  {
    id: "td_clutch_slip",
    name: "Clutch slipping",
    nameId: "Kopling Selip / Tenaga Tidak Tersalurkan",
    status: "NORMAL",
  },
  {
    id: "td_brake_pedal_stroke",
    name: "Brake pedal less functional",
    nameId: "Jarak Main / Tekanan Pedal Rem Tidak Normal",
    status: "NORMAL",
  },
  {
    id: "td_brake_performance",
    name: "Brake less functional",
    nameId: "Daya Cengkeram Pengereman Kurang Pakem",
    status: "NORMAL",
  },
  {
    id: "td_suspension_noise",
    name: "Suspension noise",
    nameId: "Bunyi Abnormal Suspensi & Kaki-Kaki",
    status: "NORMAL",
  },
  {
    id: "td_clutch_noise",
    name: "Clutch noise",
    nameId: "Bunyi Abnormal Kopling / Release Bearing",
    status: "NORMAL",
  },
  {
    id: "td_steering_noise",
    name: "Steering noise",
    nameId: "Bunyi Abnormal Sistem Kemudi / Rack Steer",
    status: "NORMAL",
  },
];
